### ISSUE TITLE
New Icon to export report definition is show only swing but not ZK

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1019]
New Icon to export report definition is show only swing but not ZK.

@dixon22ma , would you help me enable this same functionality to ZK viewer please ?

![captura de pantalla 2017-05-03 a la s 13 48 27](https://cloud.githubusercontent.com/assets/786968/25681021/b2596578-3007-11e7-903b-6309263c7956.png)

**Comment by dixon22ma** [comment]
Hello, for this issue, the IsCanLoad column was added in the AD_Role table, so that you can configure whether or not a role can load report data. 
![image](https://cloud.githubusercontent.com/assets/2453563/25964049/897b8050-3651-11e7-860d-7e91b8fee4ec.png)

If the role of the user is labeled "Can Load" the user will have the option to load and export the data of the print format in an arxml file. 
![image](https://cloud.githubusercontent.com/assets/2453563/25964141/d4d9a3d8-3651-11e7-8959-0ba1b3d0d995.png)

If the role has configured that can not "Load" the user will not have these options in the report.
![image](https://cloud.githubusercontent.com/assets/2453563/25964262/47ae945e-3652-11e7-9425-71c8042063af.png)

These options are already available in the ADempiere web environment

![image](https://cloud.githubusercontent.com/assets/2453563/25964389/b2c78cbe-3652-11e7-978b-1e4291d94bb6.png)

**Comment by dixon22ma** [comment]
Hi @e-Evolution.
 I have already committed the changes.
