### ISSUE TITLE
Bugfix the ZK not work jasper report included in print format.

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1113]
1.- Created a print report process based on jasper report
2.- Create a new print format and link with report process based on jasper
3.- The Jasper report use Record_ID as parameter to print of report.
4.- Select the report of print format list

The current issue is that the process dialog is show and not execute of report.

**Comment by e-Evolution** [comment]
The process dialog is show when no exist a parameter and if is executed not get the report

![i431 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/786968/27096250-02f22f30-5036-11e7-82d6-55d9e12eeaec.png)

**Comment by e-Evolution** [comment]
Issue related Process Dialog is not MVC #571

**Comment by marcalwestf** [comment]
The class _org.adempiere.webui.apps.WProcessCtl_ is implemented now in such a way that a Jasper Report gets **never** executed. See code:
![20180412_bug_01](https://user-images.githubusercontent.com/1789408/38659474-ff63d900-3de6-11e8-93cb-191084379d82.png)

As can easily be seen, the execution of the process (via calling _processModalDialog.runProcess()_ ) is never reached.

This bug is solved by eliminating the _else_ part:
```
ProcessModalDialog processModalDialog = new ProcessModalDialog(asyncProcess, windowNo, pi);
		if (processModalDialog.isValidDialog())
		{
			processModalDialog.setWidth("500px");
			processModalDialog.setVisible(true);
			processModalDialog.setPosition("center");
			processModalDialog.setAttribute(Window.MODE_KEY, Window.MODE_MODAL);
			AEnv.showWindow(processModalDialog);
			if (!processModalDialog.isOK()) {
				return;
			}
		}
		processModalDialog.runProcess();
		
		return;
```
