### ISSUE TITLE
Change "Create From" UI for Form like Dialog in window without "hardcode"

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#114]
The create from dialogs in window is hardcoded and it is used instead the form defined dynamically.
By default, the forms is launched in window like a CFrame and it must be like CDialog.

**Comment by e-Evolution** [comment]
Hi Yamel , I found bug for all create from window , the issue is that the context variables not work as with original functionality.

The problem is that now when open a from from a grid window the system create a new Window No for Form , but before was use Window No of the grid window, it cause an strange behavior, because try search context variable that not found this window i.e.

Create a material receipt using create from , before the locator had default value because take warehouse from grid window but not found because have a new window no then the values is null , it cause strange behavior when try process of lines.

**Comment by taherelhossin** [comment]
The same here, thank you e-Evolution

**Comment by yamelsenih** [comment]
It will be change to Smart Browse, referenced in #296
