### ISSUE TITLE
Function without compilation

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1168]
When i try recompile DB object for oracle i found a error:

**Recompile Database Objects
Recompile Functions, Procedures, Triggers, Views, etc.
** Process failed: ( INVOICEOPEN INVOICEOPENTODATE INVOICEPAID INVOICEPAIDTODATE PAYMENTALLOCATED PAYMENTAVAILABLE PRODQTYRESERVED FACT_ACCT_BALANCE_UPDATE RV_BPARTNEROPEN RV_OPENITEM RV_PAYMENT )**

**Comment by yamelsenih** [comment]
The function are:
- INVOICEOPEN
- INVOICEOPENTODATE
- INVOICEPAID
- INVOICEPAIDTODATE
- PAYMENTALLOCATED
- PAYMENTAVAILABLE

Some use Oracle?

I will fix it

**Comment by yamelsenih** [comment]
It was solved with it issue #1164

**Comment by testiranje1234** [comment]
I was and only two have error
[image: Убаци слике 1]

2017-06-23 17:08 GMT+02:00 Yamel Senih <notifications@github.com>:

**Comment by testiranje1234** [comment]
one PRODQTYRESERVED and next PRODQTYORDERED, others function oracle is ok
error is on printscr

2017-06-23 22:08 GMT+02:00 test33 test33 <testiranje1234a@gmail.com>:

**Comment by testiranje1234** [comment]
oracle database from 22062017 1800 with completed RUN_MigrationXML.sh

2017-06-23 22:09 GMT+02:00 test33 test33 <testiranje1234a@gmail.com>:

**Comment by yamelsenih** [comment]
Hi @testiranje1234 i reaply 02810_1144_New_Report_OpenItemToDate.xml and it is worked, note that i have the last source code

**Comment by testiranje1234** [comment]
function PRODQTYRESERVED give
Compilation failed,line 63 (14:12:22)
PL/SQL: ORA-00904: "S"."M_LOCATOR_ID": invalid identifierCompilation
failed,line 59 (14:12:22)
PL/SQL: SQL Statement ignored

2017-06-23 22:11 GMT+02:00 test33 test33 <testiranje1234a@gmail.com>:

**Comment by yamelsenih** [comment]
Hi @testiranje1234 i solve it on https://github.com/adempiere/adempiere/commit/3b110b0d71f2e94a67c5fab6e427ddbe3501d9fb just delete the migration record and import 00510_690_Manufacturing_light_fixes.xml

**Comment by testiranje1234** [comment]
PRODQTYORDERED oracle apex 511 didnt found error and compile is ok, but sql
developer on host of virtual machine where is basa lovated give error-
strange
?

2017-06-23 22:16 GMT+02:00 test33 test33 <testiranje1234a@gmail.com>:

**Comment by testiranje1234** [comment]
...where is database 11g xe located and install...

2017-06-23 22:21 GMT+02:00 test33 test33 <testiranje1234a@gmail.com>:

**Comment by testiranje1234** [comment]
63 line:
AND EXISTS (SELECT * FROM M_LOCATOR l WHERE s.M_Locator_ID=l.M_Locator_ID

should be s->p
p.M_Locator_ID ?



desc M_PRODUCTIONLINEM

M_PRODUCTIONLINEM_PRODUCTIONLINE_IDNUMBER - 1001 - - -  AD_CLIENT_IDNUMBER
- 100 - - - -  AD_ORG_IDNUMBER - 100 - - - -  ISACTIVECHAR1 - - - - 'Y' -
CREATEDDATE7 - - - - SYSDATE -  CREATEDBYNUMBER - 100 - - - -  UPDATEDDATE7
- - - - SYSDATE -  UPDATEDBYNUMBER - 100 - - - -  M_PRODUCTIONPLAN_IDNUMBER
- 100 - [image: nullable]NULL -  LINENUMBER - 100 - - - -  M_PRODUCT_IDNUMBER
- 100 - - - -  MOVEMENTQTYNUMBER22 - - - - 0 -  M_LOCATOR_IDNUMBER - 100 -
- - -  DESCRIPTIONNVARCHAR2255 - - - [image: nullable] - -
M_ATTRIBUTESETINSTANCE_IDNUMBER - 100 - [image: nullable]0 -  PROCESSEDCHAR1
- - - - 'N' -  M_PRODUCTION_IDNUMBER - 100 - - - -  PLANNEDQTYNUMBER22 - -
- [image: nullable]NULL -  QTYUSEDNUMBER22 - - - [image: nullable]NULL -
ISENDPRODUCTCHAR1 - - - [image: nullable]NULL -  PICKEDQTYNUMBER22 - -
- [image:
nullable]0 -  QTYRESERVEDNUMBER22 - - - [image: nullable]NULL -
C_PROJECT_IDNUMBER - 100 - [image: nullable]NULL -  C_PROJECTPHASE_IDNUMBER
- 100 - [image: nullable]NULL -  C_PROJECTTASK_IDNUMBER - 100 - [image:
nullable]NULL -  USER1_IDNUMBER - 100 - [image: nullable]NULL -  USER2_IDNUMBER
- 100 - [image: nullable]NULL -  USER3_IDNUMBER - 100 - [image: nullable]NULL
-  USER4_IDNUMBER - 100 - [image: nullable]NULL -  C_ACTIVITY_IDNUMBER -
100 - [image: nullable]NULL -  C_CAMPAIGN_IDNUMBER - 100 - [image:
nullable]NULL
-  AD_ORGTRX_IDNUMBER - 100 - [image: nullable]NULL -




create or replace FUNCTION prodQtyReserved
(
    p_Product_ID         IN NUMBER,
    p_Warehouse_ID        IN NUMBER,
    p_Locator_ID        IN NUMBER    --    Only used, if warehouse is null
)
RETURN NUMBER
/******************************************************************************
 * ** Compiere Product **             Copyright (c) 1999-2001 Accorto, Inc.
USA
 * Open  Source  Software        Provided "AS IS" without warranty or
liability
 * When you use any parts (changed or unchanged), add  "Powered by
Compiere" to
 * your product name;  See license details
http://www.compiere.org/license.html
 ******************************************************************************
 *    Return quantity reserved for BOM
 */
AS
    v_Warehouse_ID        NUMBER;
     v_Quantity            NUMBER := 99999;    --    unlimited
    v_IsBOM                CHAR(1);
    v_IsStocked            CHAR(1);
    v_ProductType        CHAR(1);
     v_ProductQty        NUMBER;
    v_StdPrecision        NUMBER;
    --    Get BOM Product info

    --
BEGIN
    --    Check Parameters
    v_Warehouse_ID := p_Warehouse_ID;
    IF (v_Warehouse_ID IS NULL) THEN
        IF (p_Locator_ID IS NULL) THEN
            RETURN 0;
        ELSE
            SELECT     MAX(M_Warehouse_ID) INTO v_Warehouse_ID
            FROM    M_LOCATOR
            WHERE    M_Locator_ID=p_Locator_ID;
        END IF;
    END IF;
    IF (v_Warehouse_ID IS NULL) THEN
        RETURN 0;
    END IF;
--    DBMS_OUTPUT.PUT_LINE('Warehouse=' || v_Warehouse_ID);

    --    Check, if product exists and if it is stocked
    BEGIN
        SELECT    IsBOM, ProductType, IsStocked
          INTO    v_IsBOM, v_ProductType, v_IsStocked
        FROM M_PRODUCT
        WHERE M_Product_ID=p_Product_ID;
        --
    EXCEPTION    --    not found
        WHEN OTHERS THEN
            RETURN 0;
    END;

    --    No reservation for non-stocked
    IF ( v_IsStocked='Y') THEN
        --    Get ProductQty
        SELECT     -1*NVL(SUM(MovementQty), 0)
          INTO    v_ProductQty
        FROM M_ProductionLine p
        WHERE M_Product_ID=p_Product_ID AND MovementQty < 0 AND p.Processed
= 'N'
          AND EXISTS (SELECT * FROM M_LOCATOR l WHERE
s.M_Locator_ID=l.M_Locator_ID
              AND l.M_Warehouse_ID=v_Warehouse_ID);
        --
        RETURN v_ProductQty;
    END IF;

    --    Unlimited (e.g. only services)
    IF (v_Quantity = 99999) THEN
        RETURN 0;
    END IF;

    IF (v_Quantity > 0) THEN
        --    Get Rounding Precision for Product
        SELECT     NVL(MAX(u.StdPrecision), 0)
          INTO    v_StdPrecision
        FROM     C_UOM u, M_PRODUCT p
        WHERE     u.C_UOM_ID=p.C_UOM_ID AND p.M_Product_ID=p_Product_ID;
        --
        RETURN ROUND (v_Quantity, v_StdPrecision);
    END IF;
    RETURN 0;
END prodQtyReserved;






2017-06-23 22:22 GMT+02:00 test33 test33 <testiranje1234a@gmail.com>:

**Comment by yamelsenih** [comment]
it is from new XML changed:

<pre>
CREATE OR REPLACE FUNCTION prodqtyordered(
    p_product_id NUMBER,
    p_warehouse_id NUMBER)
  RETURN NUMBER AS
  
	v_Warehouse_ID			NUMBER;
 	v_Quantity				NUMBER := 99999;	--	unlimited
	v_IsBOM					CHAR(1);
	v_IsStocked				CHAR(1);
	v_ProductType			CHAR(1);
 	v_ProductQty			NUMBER;
	v_StdPrecision			NUMBER;
BEGIN
	--	Check Parameters
	v_Warehouse_ID := p_Warehouse_ID;
	IF (v_Warehouse_ID IS NULL) THEN
		RETURN 0;
	END IF;
--	DBMS_OUTPUT.PUT_LINE('Warehouse=' || v_Warehouse_ID);

	--	Check, if product exists and if it is stocked
	BEGIN
		SELECT	IsBOM, ProductType, IsStocked
		  INTO	v_IsBOM, v_ProductType, v_IsStocked
		FROM M_PRODUCT
		WHERE M_Product_ID=p_Product_ID;
		--
	EXCEPTION	--	not found
		WHEN OTHERS THEN
			RETURN 0;
	END;

	--	No reservation for non-stocked
	IF (v_IsStocked='Y') THEN
		--	Get ProductQty
		SELECT 	NVL(SUM(MovementQty), 0)
		  INTO	v_ProductQty
		FROM 	M_ProductionLine p
		WHERE M_Product_ID=p_Product_ID AND MovementQty &gt; 0 AND p.Processed = 'N'
		  AND EXISTS (SELECT * FROM M_LOCATOR l WHERE p.M_Locator_ID=l.M_Locator_ID
		  	AND l.M_Warehouse_ID=v_Warehouse_ID);
		--
		RETURN v_ProductQty;
	END IF;

	--	Unlimited (e.g. only services)
	IF (v_Quantity = 99999) THEN
		RETURN 0;
	END IF;

	IF (v_Quantity &gt; 0) THEN
		--	Get Rounding Precision for Product
		SELECT 	NVL(MAX(u.StdPrecision), 0)
		  INTO	v_StdPrecision
		FROM 	C_UOM u, M_PRODUCT p
		WHERE 	u.C_UOM_ID=p.C_UOM_ID AND p.M_Product_ID=p_Product_ID;
		--
		RETURN ROUND (v_Quantity, v_StdPrecision);
	END IF;
	RETURN 0;
END prodqtyordered;
</pre>

**Comment by testiranje1234** [comment]
work ok
[image: Убаци слике 1]

2017-06-23 22:32 GMT+02:00 test33 test33 <testiranje1234a@gmail.com>:

**Comment by yamelsenih** [comment]
Please se the 00510_690_Manufacturing_light_fixes.xml

**Comment by yamelsenih** [comment]
Nice

**Comment by testiranje1234** [comment]
now working good

**Comment by testiranje1234** [comment]
Yamel, here in Serbia is colective holidays, so we need localy testers who
can contribute development adempiere in Serbia, so I make pdf instruction.
What you think about that?
Idea is simple every two days, volunters will download code, rebuild, watch
log files and make comments on https://gitter.im/adempiere/adempiere

2017-06-23 22:35 GMT+02:00 Yamel Senih <notifications@github.com>:

**Comment by testiranje1234** [comment]
I m download 24062017 all code, re-build and run setum, swing work perfect,
but have web ui no database connection


2017-06-24 9:43 GMT+02:00 test33 test33 <testiranje1234a@gmail.com>:

**Comment by testiranje1234** [comment]
uuups, wrong oracle schema, its correct 24062017, and log files in attached

-----------> MMigration.apply: Migration 143 - Update View Demand  #401 -
3.9.0 (EE03) ; Step: 100; Type: SQL.  Application failed.
java.sql.SQLException: ORA-06550: line 5, column 3:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the
following:

   ; <an identifier> <a double-quoted delimited-identifier>
The symbol ";" was substituted for "end-of-file" to continue.
 [1]
04:54:55.726   MMigration.apply: Migration 143 - Update View Demand  #401 -
3.9.0 (EE03) ; Step: 109; Type: SQL.  ---> Migration Step unapplied -
skipping. [1]
04:54:55.751   MMigration.apply: Migration 143 - Update View Demand  #401 -
3.9.0 (EE03) ; Step: 108; Type: SQL.  ---> Migration Step unapplied -
skipping. [1]
04:54:55.774   MMigration.apply: Migration 143 - Update View Demand  #401 -
3.9.0 (EE03) ; Step: 107; Type: SQL.  ---> Migration Step unapplied -
skipping. [1]
04:54:55.796   MMigration.apply: Migration 143 - Update View Demand  #401 -
3.9.0 (EE03) ; Step: 106; Type: SQL.  ---> Migration Step unapplied -
skipping. [1]
04:54:55.821   MMigration.apply: Migration 143 - Update View Demand  #401 -
3.9.0 (EE03) ; Step: 105; Type: SQL.  ---> Migration Step unapplied -
skipping. [1]
04:54:55.844   MMigration.apply: Migration 143 - Update View Demand  #401 -
3.9.0 (EE03) ; Step: 103; Type: SQL.  ---> Migration Step unapplied -
skipping. [1]
04:54:55.868   MMigration.apply: Migration 143 - Update View Demand  #401 -
3.9.0 (EE03) ; Step: 102; Type: SQL.  ---> Migration Step unapplied -
skipping. [1]
04:54:55.895   MMigration.apply: Migration 143 - Update View Demand  #401 -
3.9.0 (EE03) ; Step: 101; Type: SQL.  ---> Migration Step unapplied -
skipping. [1]
04:54:55.920   MMigration.apply: Migration 143 - Update View Demand  #401 -
3.9.0 (EE03) ; Step: 101; Type: SQL.  ---> Migration Step unapplied -
skipping. [1]
04:54:55.939   MMigrationStep.apply: Applying migration step: Migration 143
- Update View Demand  #401 - 3.9.0 (EE03) ; Step: 100; Type: SQL.  [1]
04:54:55.943   MIssue.create: Migration 143 - Update View Demand  #401 -
3.9.0 (EE03) ; Step: 100; Type: SQL.  Application failed.
java.sql.SQLException: ORA-06550: line 5, column 3:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the
following:

   ; <an identifier> <a double-quoted delimited-identifier>
The symbol ";" was substituted for "end-of-file" to continue.
 [1]
04:54:55.943   GridField.loadLookup: (SystemStatus) [1]
===========> MMigrationStep.applySQL: Migration 143 - Update View Demand
#401 - 3.9.0 (EE03) ; Step: 100; Type: SQL.  Application failed.
java.sql.SQLException: ORA-06550: line 5, column 3:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the
following:

   ; <an identifier> <a double-quoted delimited-identifier>
The symbol ";" was substituted for "end-of-file" to continue.
 [1]
-----------> MMigration.apply: Migration 143 - Update View Demand  #401 -
3.9.0 (EE03) ; Step: 100; Type: SQL.  Application failed.
java.sql.SQLException: ORA-06550: line 5, column 3:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the
following:

   ; <an identifier> <a double-quoted delimited-identifier>
The symbol ";" was substituted for "end-of-file" to continue.
 [1]
04:54:55.960   MMigration.updateStatus: Migration 143 - Update View Demand
#401 - 3.9.0 (EE03)  ---> Partially Applied (P) [1]
04:54:55.964   MMigration.updateStatus: Migration 143 - Update View Demand
#401 - 3.9.0 (EE03)  ---> Partially Applied (P) [1]
04:54:55.965 MigrationApply.addLog: 0 - null - null - Migration 143 -
Update View Demand  #401 - 3.9.0 (EE03) ; Step: 100; Type: SQL.
Application failed.
java.sql.SQLException: ORA-06550: line 5, column 3:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the
following:

   ; <an identifier> <a double-quoted delimited-identifier>
The symbol ";" was substituted for "end-of-file" to continue.
 [1]
04:54:55.968   MIssue.create: Migration 143 - Update View Demand  #401 -
3.9.0 (EE03) ; Step: 100; Type: SQL.  Application failed.
java.sql.SQLException: ORA-06550: line 5, column 3:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the
following:

   ; <an identifier> <a double-quoted delimited-identifier>
The symbol ";" was substituted for "end-of-file" to continue.
 [1]
04:54:55.968   GridField.loadLookup: (SystemStatus) [1]
===========> MigrationApply.process: Migration 143 - Update View Demand
#401 - 3.9.0 (EE03) ; Step: 100; Type: SQL.  Application failed.
java.sql.SQLException: ORA-06550: line 5, column 3:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the
following:

   ; <an identifier> <a double-quoted delimited-identifier>
The symbol ";" was substituted for "end-of-file" to continue.
 [1]
org.adempiere.exceptions.AdempiereException: Migration 143 - Update View
Demand  #401 - 3.9.0 (EE03) ; Step: 100; Type: SQL.  Application failed.
java.sql.SQLException: ORA-06550: line 5, column 3:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the
following:

   ; <an identifier> <a double-quoted delimited-identifier>
The symbol ";" was substituted for "end-of-file" to continue.

    at org.compiere.model.MMigration.apply(MMigration.java:172)
    at org.compiere.model.MMigration.apply(MMigration.java:170)
    at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
    at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
    at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
    at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
    at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
    at
org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
    at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
    at
org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:213)
    at
org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
    at
org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:286)
    at org.compiere.util.Trx.run(Trx.java:527)
    at
org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:283)
    at
org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
    at
org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
    at org.compiere.util.Trx.run(Trx.java:527)
    at org.compiere.util.Trx.run(Trx.java:495)
    at
org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
    at
org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
    at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
    at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
    at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
caused by: org.adempiere.exceptions.AdempiereException: Migration 143 -
Update View Demand  #401 - 3.9.0 (EE03) ; Step: 100; Type: SQL.
Application failed.
java.sql.SQLException: ORA-06550: line 5, column 3:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the
following:

   ; <an identifier> <a double-quoted delimited-identifier>
The symbol ";" was substituted for "end-of-file" to continue.

    at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:396)
    at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
    at org.compiere.model.MMigration.apply(MMigration.java:151)
    at org.compiere.model.MMigration.apply(MMigration.java:170)
    at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
    at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
    at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
    at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
    at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
    at
org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
    at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: java.sql.SQLException: ORA-06550: line 5, column 3:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the
following:

   ; <an identifier> <a double-quoted delimited-identifier>
The symbol ";" was substituted for "end-of-file" to continue.
; State=65000; ErrorCode=6550
    at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:447)
    at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
    at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:951)
    at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:513)
    at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227)
    at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
    at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:195)
    at
oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:1036)
    at
oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1336)
    at
oracle.jdbc.driver.OracleStatement.executeUpdateInternal(OracleStatement.java:1845)
    at
oracle.jdbc.driver.OracleStatement.executeUpdate(OracleStatement.java:1810)
    at
oracle.jdbc.driver.OracleStatementWrapper.executeUpdate(OracleStatementWrapper.java:294)
    at
com.mchange.v2.c3p0.impl.NewProxyStatement.executeUpdate(NewProxyStatement.java:64)
    at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:365)
    at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
    at org.compiere.model.MMigration.apply(MMigration.java:151)
    at org.compiere.model.MMigration.apply(MMigration.java:170)
    at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
    at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
    at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
    at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)

04:54:55.992 Trx.rollback: **** TrxRun_1a3229c6-7c26-4aac-bc16-afaef5c741d1
[1]
04:54:55.993   MIssue.create: Loading Migration from XML failed. [1]
04:54:55.993   GridField.loadLookup: (SystemStatus) [1]
===========> MigrationFromXML.process: Loading Migration from XML failed.
[1]
org.adempiere.exceptions.AdempiereException: Loading migration from
/home/nadrog/Adempiere/migration/380lts-release/00143_401_UpdateDemandView.xml
failed.
    at
org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:168)
    at org.compiere.util.Trx.run(Trx.java:527)
    at org.compiere.util.Trx.run(Trx.java:495)
    at
org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
    at
org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
    at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
    at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
    at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
    at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
    at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
    at
org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
    at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: org.adempiere.exceptions.AdempiereException: Process failed
during execution Error:  Migration 143 - Update View Demand  #401 - 3.9.0
(EE03) ; Step: 100; Type: SQL.  Application failed.
java.sql.SQLException: ORA-06550: line 5, column 3:
PLS-00103: Encountered the symbol "end-of-file" when expecting one of the
following:

   ; <an identifier> <a double-quoted delimited-identifier>
The symbol ";" was substituted for "end-of-file" to continue.

    at
org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:294)
    at
org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
    at
org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
    at org.compiere.util.Trx.run(Trx.java:527)
    at org.compiere.util.Trx.run(Trx.java:495)
    at
org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
    at
org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
    at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
    at org.compiere.process.SvrProcess.process(SvrProcess.java:171)
    at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:124)
    at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)


*** 2017-06-24 04:54:56.015 Adempiere Log (CLogFile) ***

2017-06-24 9:55 GMT+02:00 test33 test33 <testiranje1234a@gmail.com>:

**Comment by testiranje1234** [comment]
error on 00143_401_UpdateDemandView.xml
sequence 100

2017-06-24 11:16 GMT+02:00 test33 test33 <testiranje1234a@gmail.com>:

**Comment by testiranje1234** [comment]
from oracle sql not right is 1, right is 2

1) select 'true' from dual where 10 &gt; 5
2) select 'true' from dual where 10>5
so 00143_401)UpdateDemandView.xml should be all compare
What other think about that?

**Comment by testiranje1234** [comment]
best way is find/replace &lt; with >  and find replace &gt; with < save and
re-migration, and error will be lost. most simple way.

2017-06-24 17:30 GMT+02:00 test33 test33 <testiranje1234a@gmail.com>:

>
> from oracle sql not right is 1, right is 2
>
> 1) select 'true' from dual where 10 &gt; 5
> 2) select 'true' from dual where 10>5
> so 00143_401)UpdateDemandView.xml should be all compare
> What other think about that?
>
>

**Comment by testiranje1234** [comment]
successfull RUN_MigrateXML.sh
with replace 00143_401_UpdateDemandView.xml for oracle database installation

2017-06-24 17:57 GMT+02:00 test33 test33 <testiranje1234a@gmail.com>:

> best way is find/replace &lt; with >  and find replace &gt; with < save
> and re-migration, and error will be lost. most simple way.
>
> 2017-06-24 17:30 GMT+02:00 test33 test33 <testiranje1234a@gmail.com>:
>
>>
>> from oracle sql not right is 1, right is 2
>>
>> 1) select 'true' from dual where 10 &gt; 5
>> 2) select 'true' from dual where 10>5
>> so 00143_401)UpdateDemandView.xml should be all compare
>> What other think about that?
>>
>>
>
