### ISSUE TITLE
Accouting Date is the now instead of invoice date

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1292]
When a vendor invoice is created from a receipt, the match Invoice don't have the same acounting date that the invoice, the follow is step by step my test:

**Test Data**
  **Business Partner**: GardenAdmin BP
  **Product**: Nitrogen

- Create Order **2017-08-08**: Nitrogen 1500 x 350 $
- Create Receipt **2017-08-08**: Nitrogen 1500
- Create Invoice from Receipt **2017-08-10**: Nitrogen 1500 x 400
 The result is:  the product cost for match invoice is created with 2017-08-08 instead 2017-08-10 like is created the invoice accounting date.

It is because the DateAcct column on match invoice is not setted from invoice when it is generated.

**Comment by marcalwestf** [comment]
Reproducing the error: even though Invoice is of a certain date, the Match PO Document inherits the date of the Order:
![20170721_adempiere_31](https://user-images.githubusercontent.com/1789408/29197933-fb4f0880-7dfc-11e7-8e91-115c3d554d17.png)
![20170721_adempiere_32](https://user-images.githubusercontent.com/1789408/29197935-ffc025b6-7dfc-11e7-9888-abece6889f80.png)

**Comment by yamelsenih** [comment]
I will fixed it also

**Comment by marcalwestf** [comment]
going to test the fix...

**Comment by marcalwestf** [comment]
now with the bug fix the Match PO takes the invoice's date:
![20170721_adempiere_34](https://user-images.githubusercontent.com/1789408/29198272-9bf76c1c-7dff-11e7-8284-9b7856e1e37b.png)

**Comment by yamelsenih** [comment]
Hi @marcalwestf please test it, see the pics:
![screenshot_20170810_210835](https://user-images.githubusercontent.com/2333092/29198308-b7001e9e-7e10-11e7-8acb-487a523eb98f.png)
![screenshot_20170810_210858](https://user-images.githubusercontent.com/2333092/29198307-b6fccdac-7e10-11e7-9f7c-07f1df51b316.png)
![screenshot_20170810_210918](https://user-images.githubusercontent.com/2333092/29198306-b6fa0e96-7e10-11e7-9e8d-4a88a7716aee.png)

**Comment by adaxa-steven** [comment]
Mario,
I would expect that the Match Invoice document needs to take the later of Receipt accounting date or Invoice accounting date or the first open accounting date if they are in a closed period.. Otherwise you will get invoice price variances etc in April on goods you have not received till May... that should confuse everyone. 
regards
steven

**Comment by ignaciomorenoc** [comment]
Now i know why you talked about this recently. Regads,

**Comment by marcalwestf** [comment]
@adaxa-steven agree on the situation you describe that a closed period should be considered.

As of now, Yamel's solution consisted of taking the _Accounting Date_ from the _Invoice_ instead of from the _Order_.
Thus, if the Invoice could not be completed because of a closed period, the Match Invoice will not proceed, neither. Due to this fact that, I'd suppose we're on the save side, as the accounting date of the Match Invoice should be the same as the Invoice's. 

These are just "academical" thoughts, not tested empirically.

**Comment by yamelsenih** [comment]
It is worked

**Comment by adaxa-steven** [comment]
Hi Mario
This is the same problem as with Payment allocation.  Invoice in February, payment in March .. allocation not done in March, March period is closed.  Allocation created in April and takes as allocation date the later of invoice and payment.  Allocation then will not post because March period is closed.

If it is going to be changed then it would better if it was later of the two document dates or first open accounting date... for the Match documents and the Payment Allocation.

Perhaps it can be fixed as above at a later date.

regards
Steven
