### ISSUE TITLE
POS: Always shows product info

### ISSUE THREAD

**Issue by ogomezislas** [adempiere/adempiere#1296]
When a product is selected through POS Product Lookup, the product info window is activated and the product can no longer be added.

The reason:
The product (with the same key) exists in two different companies
Comparing AD_Client_ID in the getQueryProduct method query does not work.(CPOS.java)

Proposed solution:
Line 2290, add comparison of AD_Client_ID
.append ("WHERE pl.M_PriceList_ID =? AND plv.IsActive = 'Y' AND pp.IsActive = 'Y' AND p.AD_Client_ID =?")

Line 2299, add comparison of AD_Client_ID
.append ("WHERE pl.M_PriceList_ID =? AND plv.IsActive = 'Y' AND pp.IsActive = 'Y' AND pp.BreakValue IN (0,1) AND p.AD_Client_ID =?")

Line 2308, remove comparison of AD_Client_ID because it is no longer needed
Sql.append ("AND p.AD_Client_ID =? AND p.IsSold =? AND p.Discontinued =?")

**Comment by yamelsenih** [comment]
Hi @ogomezislas the query is ok, the problem is because exist a OR statement for all query instead of simple criteria, see:

<pre>
.append("AND UPPER(p.Name)  LIKE UPPER('").append("%").append(productCode.replace(" ","%")).append("%").append("')")
.append(" OR UPPER(p.Value) LIKE UPPER('").append("%").append(productCode.replace(" ","%")).append("%").append("')")
.append(" OR UPPER(p.UPC)   LIKE UPPER('").append("%").append(productCode.replace(" ","%")).append("%").append("')")
.append(" OR UPPER(p.SKU)   LIKE UPPER('").append("%").append(productCode.replace(" ","%")).append("%").append("')");
</pre>

**Comment by yamelsenih** [comment]
The current query have it:

<pre>
AND C_BPartner_ID IS NULL 
AND p.AD_Client_ID=11 
AND p.IsSold= 'Y'
AND p.Discontinued='N' 
AND UPPER(p.Name)  LIKE UPPER('%ASS%') 
OR UPPER(p.Value) LIKE UPPER('%ASS%') 
OR UPPER(p.UPC)   LIKE UPPER('%ASS%') 
OR UPPER(p.SKU)   LIKE UPPER('%ASS%')
</pre>

It should be changed to:

<pre>
AND C_BPartner_ID IS NULL 
AND p.AD_Client_ID=11 
AND p.IsSold= 'Y'
AND p.Discontinued='N' 
AND 
(
UPPER(p.Name)  LIKE UPPER('%ASS%') 
OR UPPER(p.Value) LIKE UPPER('%ASS%') 
OR UPPER(p.UPC)   LIKE UPPER('%ASS%') 
OR UPPER(p.SKU)   LIKE UPPER('%ASS%')
)
</pre>

**Comment by yamelsenih** [comment]
Hi @ogomezislas please test it for close

**Comment by yamelsenih** [comment]
It is ok
