### ISSUE TITLE
Financial Report not have a Posting Type as parameter

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#1302]
The financial report have many parameter for launch.

But i want launch a **General Balance** and **Lost and Gain** based on budget? Currently the Posting Type is defined in **Report Column** and **Report Line**.

I propose add the Posting Type and Budget reference  as parameter for report and overwrite the default report configuration when the parameters is filled

**Comment by adaxa-steven** [comment]
Hi Yamel,
An alternative view...
You can create the report you want by defining a Financial Report that identifies in its name that it is printing Budget numbers and select Budget Posting Type in the column definition.
If you add Posting Type as a parameter on the lead-in page and run it against a Financial Report where the Column (and perhaps the Lines) are defined as Actual then it will most likely confuse users not expecting such behaviour.
If a user selects Posting Type=Budget on the parameters on a Financial Report that prints Actual, Budget, Variance .. what would you expect the report to do?

I request that you put the proposal to be considered by the Functional Group so it can be more deeply considered and either accepted or rejected.

regards
steven

**Comment by yamelsenih** [comment]
Hi @adaxa-steven the parameters can overwrite the report configuration like is **Print Source first** parameter

**Comment by yamelsenih** [comment]
@adaxa-steven can you help me to identify the Ax_Case column in T_Report table?

**Comment by adaxa-steven** [comment]
Hi Yamel,
Ax_Case was added to return a value of B (balance sheet) if Account Type was (A)sset (L)iabilty or (O)wner Equity .(or maybe we did it on (R)evenue and (Expense) I forget).. then I could use it in a List report that summed by BorP group, Account Type, and Account.  This then provided an easy check of the sum of transactions so I could compare to (say) a 'Financial Report - Balance Sheet' to make sure no accounts were in the wrong place in the account tree or not in the account tree, or had wrong Account Type... and because it was running against a Cube of '0rg+Account' the number of rows was very small so it ran very fast. 

Initially the window that displayed the content of the Report Cube looked at the Table.  We later changed it for adaxa so that Window looked at a View instead.  In the View we added the BorP case statement, Account Type, and resolved Account code so that we could say "from Account" and "To Account".  This made the window displaying the Cube contents much more useful.

regards
Steven

**Comment by yamelsenih** [comment]
Hi @adaxa-steven thank you for explain it

**Comment by adaxa-steven** [comment]
Yamel,
some extra info I just remembered ... the 'Case' and 'Account type' were added by mistake to the table when they should only have existed in the view .. for some reason every time I got them deleted from the table they would return at a later date ;-(
If they are in the table in 390 they should be dropped.
regards

**Comment by yamelsenih** [comment]
Thank you Steven, I will to delete it.

**Comment by adaxa-steven** [comment]
i notice in 390 there is no report and process that lets you report or export the contents of the report cube.  It is a helpful report and could be added
These are the paremeters 
![image](https://user-images.githubusercontent.com/15791084/29500358-6d9655d8-8663-11e7-8da3-a31788cc23eb.png)
 and this is the report

 
![image](https://user-images.githubusercontent.com/15791084/29500374-88fd22a2-8663-11e7-981c-bb6927e62229.png)

or with summary ticked
![image](https://user-images.githubusercontent.com/15791084/29500381-9d2b6a90-8663-11e7-81f5-a4751267c549.png)

very useful.

**Comment by yamelsenih** [comment]
Hi @adaxa-steven i add four parameter for overwrite **Financial Report** se the pic:

![screenshot_20170820_233532](https://user-images.githubusercontent.com/2333092/29502779-85475afa-8600-11e7-949c-571a993d3307.png)

Also, how now exist **List Sources** and **List Trx** in Report Line, the same values now are optional in **Financial Report**, see:

![screenshot_20170820_234008](https://user-images.githubusercontent.com/2333092/29502850-06be6182-8601-11e7-8ad2-d67702d8dcc5.png)

The hierarchy is:

- For Posting Type and optional Budget:
  1. If report parameter is setted, it overwrite all.
  2. If report parameter is not setted then the report line is used as value.
  3. If report line is not setted then the report column is used.
- For **List Source** and **List Trx**:
  1. If report parameter is setted, it overwrite all configuration.
  2. If report parameter is not setted then the report configuration is used for list or not.
  3. If the report configuration is not setted then the report line is used for list or not.

Best regards

**Comment by yamelsenih** [comment]
Steven i will review it

> i notice in 390 there is no report and process that lets you report or export the contents of the report cube. It is a helpful report and could be added

**Comment by yamelsenih** [comment]
Hi @adaxa-steven i create the issue #1307 for delete **Ax_Case** column

**Comment by e-Evolution** [comment]
Hi @yamelsenih Yamel I am agree with Steven @adaxa-steven , I not am sure that adding the Posting Type as parameters because it should be setting into each column or row definition, this reason that exist in rows and columns.

The definition into row or column was think to can create columns that can be compares between they , for example real vs budget , and budget vs budget .

So the definition to depended of each financial report. 

If we adding as parameters the report no will work as was defined.
therefore  the designers of  the financinal reports should know  that want get.

We would get same result if we adding the posting type into Report Cube , so you no need defined as parameter because report cube would be only for budget , actual , statistical , etc. and use this report cube when get the report.

So I think that adding the parameters posting type , and budget not is good idea, I vote to include this into report cube and use report cube to generate the report.

**Comment by yamelsenih** [comment]
Hi, it is just like a filter, if you not setted it the the financial report is the same but if you want a financial report that is configured for actual posting can show as budget posting then you must create other report, with it parameter you can use the same report and make a filter by posting type
