### ISSUE TITLE
Initial client setup process is not scrollable

### ISSUE THREAD

**Issue by ishanuda** [adempiere/adempiere#131]
Hi,
i have checked out the ADempiere 3.8.0 and it appears that Initial client setup process window has no scrollbar and when we are to create a new client some fields are hidden.

The screen as shown,

![initial client setup process](https://cloud.githubusercontent.com/assets/8893919/11415706/343a5b66-942c-11e5-85d7-547d5111f717.jpg)

**Comment by mckayERP** [comment]
Thanks for reporting the issue.  This was fixed as part of ADEMPIERE-407 in hotfix1. The fix was committed on 25 Apr 2015 (7229ae637a).  A binary with that fix has not been officially published but you can try [this intermediate version](https://bintray.com/artifact/download/mckayerp/ADempiere-444-Window-Install-Test/Adempiere_380LTS_2.zip).

**Comment by ishanuda** [comment]
Thank you very much for the reply.
