### ISSUE TITLE
POS getSalesRep from customer

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#1314]
Actually the sales rep of a new order is the salesrep defined in the POS Terminal. 
It should be possible to use the salesrep from the businesspartner.
Solution:
A new column in C_POS _IsChangeSalesRep_

Class CPOS method configureBPartner, line 831
```

//	Set Sales Representative
			if (currentOrder.getC_BPartner().getSalesRep_ID() == 0||
					!entityPOS.get_ValueAsBoolean("IsChangeSalesRep"))
					currentOrder.setSalesRep_ID(entityPOS.getSalesRep_ID());
			//	Save Header

```
Class WPOSDocumentPanel,refreshPanel,  line 415
`

			salesRep.setText(posPanel.getOrder().getSalesRep().getName());`

**Comment by e-Evolution** [comment]
@SusanneCalderon I revert your commits because not following the ADempiere best practices please check your code page or eclipse settings because some java code  that change change all code you can see here : 

![captura de pantalla 2017-08-31 a la s 13 26 13](https://user-images.githubusercontent.com/786968/29938973-06cf0404-8e50-11e7-82f6-a514f150add4.png)

Other issue is that not are adding the url of GitHub issue that is requirements 

![captura de pantalla 2017-08-31 a la s 13 27 41](https://user-images.githubusercontent.com/786968/29939037-34382484-8e50-11e7-82de-b95b89d2b448.png)
