### ISSUE TITLE
HTTP Status 500 when a ROLE is changed.

### ISSUE THREAD

**Issue by PMillanFurryWolf** [adempiere/adempiere#1347]
Hello team.

A few days ago while I was working with the version 3.9.0, I tried the feature in the main page called "Change Role", but the web browser gave me a HTTP status 500 showing this: 
![cap](https://user-images.githubusercontent.com/15034587/30987193-bbf8d05a-a45b-11e7-90c6-acd3b5c913da.JPG)

Do you have an idea about this bug?

Blessing :)

**Comment by PMillanFurryWolf** [comment]
Looking up in the path: zkwebui\WEB-INF\src\org\adempiere\webui\window, in the class called LoginWindow.java, I found a possible way to fix this bug.

In the line 133 from this file I found this;

`String loginName = user.getLDAPUser() != null ? user.getLDAPUser() : user.getName();`
This data is retrieved from the user name than has logged in ADempiere, and when I try change the role, I have again the HTTP 500 status, so I tried modifying this line to retreive the User Pin instead the User name, obtaining this code modification:

`String loginName = user.getUserPIN();`

and with this I don't have the HTTP 500 status anymore. what do you thing?

Blessing :)

**Comment by yamelsenih** [comment]
Hi @PMillanFurryWolf i fixed it with last commit, please test it and confirm issue for close.
Details: only add a missing lines from new login apporach:
<pre>
boolean loginWithValue = M_Element.get(Env.getCtx(), I_AD_User.COLUMNNAME_IsLoginUser) != null;
String loginName = null;
if(user.getLDAPUser() != null) {
	loginName = user.getLDAPUser();
} else if(loginWithValue) {
	loginName = user.getValue();
} else {
	loginName = user.getName();
}
</pre>
The problem was that if a user have a **Name** distinct to **Value** then it is reject from login. See the image and note that the name have **space** but login is ok:
![screenshot_20171113_012645](https://user-images.githubusercontent.com/2333092/32710960-a48bdd56-c812-11e7-913d-8a05818f3316.png)
![screenshot_20171113_012710](https://user-images.githubusercontent.com/2333092/32710959-a4708894-c812-11e7-9df3-9898cd545ddc.png)

**Comment by PMillanFurryWolf** [comment]
Excelent and clever way to fix it, Thanks @yamelsenih
