### ISSUE TITLE
Implement Reverse Accrual for all document that generate account fact

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1348]
Currently, the system when doing a reverse correction is done validating if the period is open and with the date of the original document, implement the reverse accrual using the date of the current period.

It is necessary to take forecasts for multi-currency documents since to revert a loss or gain in exchange, should be with the original date of the document so that the reverse is correct.

My proposal to solve this issue is simple we can to add the currency rate in any document and using this to calculate the reverse a loss or gain in exchange.

**Comment by e-Evolution** [comment]
First Stage Implement Reverse Accrual for Shipment / Material Receipts ,  Customer Invoice , Vendor Invoice and payment allocations.

Tests to be performed

Purchasing process

1.- Create Purchase Order , Created Material Receipt based on PO. and Create Vendor Invoice based on  Created Material Receipt , Reverse Correction Vendor Invoice , Reverse Correction Material Receipt.

2.- Create Purchase Order , Created Material Receipt based on PO. and Create Vendor Invoice based on  Created Material Receipt , Reverse accrual Vendor Invoice , Reverse accrual Material Receipt.

3.- Create Purchase Order , Create Vendor Invoice based on PO, Created Material Receipt based on vendor invoice,  Reverse Correction Material Receipt and next Reverse Correction Vendor Invoice.

4.- Create Purchase Order , Create Vendor Invoice based on PO, Created Material Receipt based on vendor invoice,  Reverse Accrual Material Receipt and next Reverse Accrual Vendor Invoice.

5.- Generate the step 1 to 4 with same Purchase Order.

6.- Generate Sales Order , Generate Shipment and Generate Customer Invoice , Reverse Correction the customer Invoice ,  Reverse Correction  of Shipment 

7.- Generate Sales Order , Generate Shipment and Generate Customer Invoice , Reverse Accrual the customer Invoice ,  Reverse Accrual  of Shipment

**Comment by adaxa-steven** [comment]
"My proposal to solve this issue is simple we can to add the currency rate in any document and using this to calculate the reverse a loss or gain in exchange."
assume exchange rate 1 june  EUR1.00 = USD1.10   and then 1 July becomes EUR1.00 = USD1.20
we have eur 100 in the bank  with accounted value of usd110
we make a payment of EUR100 and now have zero in the bank. (assume the payment is not allocated)

we reverse correct the payment on 2 July
we now have eur100 in the bank but its value is USD120

the -100 eur gets matched to the +100 eur and we get a usd10 exchange gain.... just reversing the payment at the old rate is not a good idea.

your steps 1 to 7 seem to be planning to reverse a set of linked documents because one has been reverse corrected?  If so that seems dangerous.  It would be safer if a reversal of a document only reversed that document and you manually reversed any related documents.

regards

**Comment by SusanneCalderon** [comment]
I tested the recommended steps, the special form Match does show the already assigned receiptlines.
The class AverageInvoiceCostingMethod cannot find the matchInv because the matchinv do not have a reference to m_Inoutline_ID. 
When I assign manually in the special form the new registers of m_Matchinv have a reference to m_Inoutline_ID.

**Comment by SusanneCalderon** [comment]
**The costing for average invoice does not work if you do not register m_Inoutline_ID in M_MatchInv.**

I tested purchase with the new code, omitting m_Inoutline_ID in m_Machtinv, for costing method average invoice.
Step 1. Create purchase order, product 1, quantity 10, price 10.25 per unity, complete
Step 2: Create material receipt based on purchase order, complete and post
Step 3: Generate purchase invoice with botton "Generate invoice"
Step 4: change price in the invoice to 11, complete and post
Step 5: When I try to post the generated m_MatchInv I get the posting error "Receipt not poste"

Resume of the acounting: (I use the same clearing account for receipt and inventory)
Invoice : Clearing account of the product -- Liabilities 110 -- 110
Receipt: Inventory -- Clearing account: 102.50 -- 102.50
The difference is not posted for the posting error.
The average cost of the product is still 10.25, because the additional costs of 0.75 are not detected, due to the missing m_Inoutline_ID on m_matchInv.

Problem: The additional costs are not included in the average costs. Legally not correct for average invoice
When I change the code in class MMatchInv so that the m_Inoutline_ID is registered in m_MatchInv the costing works correctly.
So I cannot test the reverseaccrual if the original posting is not correct. 

**As the ommission of m_inoutline_ID in m_MatchInv create severe problems I suggest to revert the code in MMatchInv.**

**Comment by SusanneCalderon** [comment]
I tested reversecorrectIt() in a running implementation. When you cancel a material receipt, generated before implementing the modifications for reverseaccrual() the costs are not updated.

**Comment by SusanneCalderon** [comment]
Summary: 

1. When you execute a reversecorrectIt in Purchase it is almost always for correction of a human error, like price error, date error, qty error... In these cases it it better to delete the matchinv, in order to avoid applying and collecting garbage in the Accounting, especially in the Product Asset account. 

2. When you are using costing method Average Invoice, and you revert a MatchInv, you must insert the corresponding Costdetail behind lastCostdetail, without considering that it is a reverting document. This is necessary for logging the new Average cost. If you revert a matchInv, in any case it is difficult to insert the matchInv at the correct position, and this is not solved in the actual version of AverageInvoice. So in case of using Average Invoice it is a better practice not to use reverse accrual, but just reversecorrectIt until these problems are solved.

3. So it is recommendable to establish the ReversecorrectIt for Invoices and Inouts as it was originally (delete matchInvs) and in case of Average Invoice only use Reverseaccrual for sales. This requires a role configuration excluding reverseaccrual for purchase.

**Comment by SusanneCalderon** [comment]
Test:
create new Product Orchidee 

Starting Point:
1. Initial Inventory items 63, Cost $56.23
2. Sale items 4, cost $56.23
3. Order and Material Receipt: items 50, cost $32
4. Sales, items 41, costs $45.11


![20180126_sc_costing_01](https://user-images.githubusercontent.com/15349639/35455574-037cb0a0-0298-11e8-9c67-18aebf9f730a.PNG)


Scenario 1, create Purchase invoice with price $36
![20180126_sc_costing_02](https://user-images.githubusercontent.com/15349639/35455594-289fe1ae-0298-11e8-8202-b92ba98d38ea.PNG)



Screnario 2, void Purchase invoice (reverseCorrectIt), Run process Generate Cost Transaction, result as starting point
![20180126_sc_costing_01](https://user-images.githubusercontent.com/15349639/35455688-83045490-0298-11e8-9b79-04a26d581096.PNG)



Scenario 3, create Purchase invoice with price $40
![20180126_sc_costing_03](https://user-images.githubusercontent.com/15349639/35455734-ab1df544-0298-11e8-9566-ef68d8850e00.PNG)

As you see, you can correct your errors by voiding without creating undesired movements in the Product Asset account.

**Comment by SusanneCalderon** [comment]
Next step is to correct material receipts. 

We have tested it: voiding a material receipt creates the correct reversal document and the report shows the incoming and corrected lines, the reversal line follows the original line as it is expected.

**Comment by SusanneCalderon** [comment]
ToDo: test and correct errors in **reverseaccrual** for **purchase** and costing method **average invoice**. 

As explained in a former comment the position of the revert document is crucial for a correct calculation of the average invoice cost.

**Comment by e-Evolution** [comment]
Hi @SusanneCalderon 

my comments  are here: 

1.- The first case would apply when the accounting  period is open , but this not is the regular practice for any document completed in ADempiere. any document that generate an accounting fact is necessary reverse , if we using this new approach then we should implement the same approach with any document that generate a accounting facts, and this is a big effort 

I think that should continue with ADempiere standard approach.

2.- Yes currently the cost engine have not implemnt accrual reversal transaction, so is necessary implement , now the cost engine search the original transaction and create a record with opposite sign, a good example is  reverse material receipt , is necesary implement this same approach  with match invoice reversal.

3.- The old approach no solve the alot issues generate accounting  cost when a period was closed and exist a problem in receipt or invoice documents.

the old approach delete the match invoice without valdiate if period is closed it cause alot of issues the financial report with period closed , the accounts amounts not should be modify if a period was closed 

The best solution is implement in cost engine the reversal document for Match Invoice as material receipt or shipments

**Comment by SusanneCalderon** [comment]
@e-Evolution 
Victor, I totally agree with you. 

The committed code corrects errors introduced with the developement of accrual. 
These errors consisted of false calculation of the costs of matchInv for costing method Average Invoice **which did work before**. You agree on this in your comment before.

The code I commited establishes the deleting of matchinv for open periods, and doc action reverseCorrectIt as it was before the development of accrual. It is a working starting point for a **correct , complete and general** improvement of the reversing funcionality, which should work for **all costing methods.**

What now has to be done is:
- Implement  for all documents the correct calculation of the costs when the last costdetail is not the original costdetail . This happens for example for the new doc Action accrual and costing method Average invoice.
- Define a correct separation of voiding methods which establishes deleting matchinv or reverting matchinv, decided by the user. So the user can decide if he is just correcting or really voiding. 
- Test thoroughly for all scenarios, document types and costing methods.
