### ISSUE TITLE
Migration Tools -> currently not preserve of the System Print Format 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#1362]
Currently if add print format as system it are deleted and should be preserved , the reason the AD_PrintFormat have not entity type

**Comment by adaxa-steven** [comment]
Hi Victor,
In case this is related and because we want to preserve the capability...
![image](https://user-images.githubusercontent.com/15791084/31325617-c56f69ca-ad0a-11e7-817a-1fdafdeed6b4.png)
we added a flag on the copy/create for printformats which creates a printformat stored at System level. The objective was to be able create more useful print formats by using the data that was available within GardenWorld and then be able to save them in System ... then later on the print format could would available in any client added to the system and it could also be packed-out and be added to trunk if we wanted.
