### ISSUE TITLE
General Ledger Report with acumulated

### ISSUE THREAD

**Issue by niclopup** [adempiere/adempiere#1366]
General Ledger with acumulated

The idea of this report is to add the Initial Acumulated Balance to the "From" date when the report is taken. For example if the the accounting starts in January and there is one transaction to some Account, now if you search for the report "Accounting Fact Detail" for February, this movemnt will not appear. But the actual Balance of this Account will include it in some Balance Sheet for exaple.

In the new report "General Ledger with Acumulated" the amount of the transaction of January will be shown in the Column "Acumulated Amount" whit all the transactions that where before the "From" date of the Report.

**Comment by e-Evolution** [comment]
Hi @niclopup @Nico , this a common requirement from accountants, currently Adempiere have no away simple to get balance from account date from any account.

So a good way to implement this is created a function that can set the account is and balance date, the other hand Adempiere support multiple dimension so that also is necessary additional support to get a balance based on a valid combination.

**Comment by adaxa-steven** [comment]
Hi 
The Trial Balance is nearly usable now....
![image](https://user-images.githubusercontent.com/15791084/31470149-5a62c1f4-af30-11e7-8a59-acd47e66154b.png)
(note that 'Date_) is a virtual column set by case when table is null then date_ is dateacct-1 else dateacct .. this forces any opening balance to be the first displayed transaction as that line has a null for table)

the problem is that that these fields (red box) have never operated as expected.
![image](https://user-images.githubusercontent.com/15791084/31470706-e14b8de0-af30-11e7-8d0d-a197fbaa1ebe.png)

**Comment by niclopup** [comment]
Hi @adaxa-steven , Thanks for your answer! This is really helpful. I verify and it's seems to be all right!

Please, let us now if there is other things pending to solve about Trial Balance.
