### ISSUE TITLE
Commission: Payment Term not implemented

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#1474]
In the Commission Definition Line it is possible to define a Payment Term.

This fact is not considered in MCommissionRun.processCommissionLine().

Solution: include Payment Term as an additional filter, similar to Product Group, Payment Rule, etc.

**Comment by e-Evolution** [comment]
@marcalwestf @SusanneCalderon 

Please need verify your end code commits , I see that is change the original file , if you see the detail into 

https://github.com/adempiere/adempiere/commit/b096090d3a5db5258acdf3a33ba408817fa667c9

Show that all file change and this nos is right because you have not a patch file this way.

the the other hand need add in each commit the url issue this way other developer can see what is the issue in GitHub

**Comment by e-Evolution** [comment]
Error when try apply script 

17:12:19.523   MMigration.updateStatus: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D)  ---> Unapplied (U) [1]
17:12:19.523   MMigration.updateStatus: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D)  ---> Unapplied (U) [1]
17:12:19.854   MMigrationStep.apply: Applying migration step: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  [1]
17:12:19.854   MMigrationStep.apply: Applying migration step: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  [1]
===========> MMigrationStep.applySQL: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:19.871   MIssue.create: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:19.871   MIssue.create: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:19.882   GridField.loadLookup: (SystemStatus) [1]
17:12:19.882   GridField.loadLookup: (SystemStatus) [1]
===========> MMigrationStep.applySQL: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
-----------> MMigration.apply: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
-----------> MMigration.apply: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:20.405   MMigration.apply: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 30; Type: SQL.  ---> Migration Step unapplied - skipping. [1]
17:12:20.405   MMigration.apply: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 30; Type: SQL.  ---> Migration Step unapplied - skipping. [1]
17:12:20.722   MMigrationStep.apply: Applying migration step: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  [1]
17:12:20.722   MMigrationStep.apply: Applying migration step: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  [1]
===========> MMigrationStep.applySQL: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:20.725   MIssue.create: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:20.725   MIssue.create: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:20.726   GridField.loadLookup: (SystemStatus) [1]
17:12:20.726   GridField.loadLookup: (SystemStatus) [1]
===========> MMigrationStep.applySQL: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
-----------> MMigration.apply: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
-----------> MMigration.apply: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:20.801   MMigration.updateStatus: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D)  ---> Unapplied (U) [1]
17:12:20.801   MMigration.updateStatus: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D)  ---> Unapplied (U) [1]
17:12:20.855   MMigration.updateStatus: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D)  ---> Unapplied (U) [1]
17:12:20.855   MMigration.updateStatus: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D)  ---> Unapplied (U) [1]
17:12:20.856 MigrationApply.addLog: 0 - null - null - Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:20.856 MigrationApply.addLog: 0 - null - null - Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
===========> MigrationApply.process: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
org.adempiere.exceptions.AdempiereException: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$
	at org.compiere.model.MMigration.apply(MMigration.java:172)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
	at org.eevolution.service.dsl.ProcessBuilder.run(ProcessBuilder.java:216)
	at org.eevolution.service.dsl.ProcessBuilder.access$200(ProcessBuilder.java:53)
	at org.eevolution.service.dsl.ProcessBuilder$1.run(ProcessBuilder.java:289)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.eevolution.service.dsl.ProcessBuilder.execute(ProcessBuilder.java:286)
	at org.compiere.process.MigrationFromXML.applyMigration(MigrationFromXML.java:181)
	at org.compiere.process.MigrationFromXML.lambda$loadFile$0(MigrationFromXML.java:163)
	at org.compiere.util.Trx.run(Trx.java:527)
	at org.compiere.util.Trx.run(Trx.java:495)
	at org.compiere.process.MigrationFromXML.loadFile(MigrationFromXML.java:141)
	at org.compiere.process.MigrationFromXML.loadXML(MigrationFromXML.java:107)
	at org.compiere.process.MigrationFromXML.doIt(MigrationFromXML.java:49)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
caused by: org.adempiere.exceptions.AdempiereException: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$
	at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:391)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)
caused by: org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$; State=42601; ErrorCode=0
	at org.postgresql.core.Parser.checkParsePosition(Parser.java:1132)
	at org.postgresql.core.Parser.parseSql(Parser.java:1021)
	at org.postgresql.core.Parser.replaceProcessing(Parser.java:973)
	at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateAction.java:41)
	at org.postgresql.core.QueryExecutorBase.createQueryByKey(QueryExecutorBase.java:304)
	at org.postgresql.core.QueryExecutorBase.createQuery(QueryExecutorBase.java:315)
	at org.postgresql.jdbc.PgConnection.createQuery(PgConnection.java:160)
	at org.postgresql.jdbc.PgStatement.addBatch(PgStatement.java:664)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.addBatch(NewProxyStatement.java:691)
	at org.compiere.model.MMigrationStep.applySQL(MMigrationStep.java:354)
	at org.compiere.model.MMigrationStep.apply(MMigrationStep.java:227)
	at org.compiere.model.MMigration.apply(MMigration.java:151)
	at org.compiere.model.MMigration.apply(MMigration.java:170)
	at org.compiere.process.MigrationApply.doIt(MigrationApply.java:53)
	at org.compiere.process.SvrProcess.process(SvrProcess.java:174)
	at org.compiere.process.SvrProcess.startProcess(SvrProcess.java:127)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:160)
	at org.adempiere.util.ProcessUtil.startJavaProcess(ProcessUtil.java:105)
	at org.compiere.process.ServerProcessCtl.startProcess(ServerProcessCtl.java:415)
	at org.compiere.process.ServerProcessCtl.run(ServerProcessCtl.java:246)

17:12:20.858   MIssue.create: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:20.858   MIssue.create: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
17:12:20.859   GridField.loadLookup: (SystemStatus) [1]
17:12:20.859   GridField.loadLookup: (SystemStatus) [1]
===========> MigrationApply.process: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$ [1]
org.adempiere.exceptions.AdempiereException: Migration 3360 - Commission functions linenetamtreal - 3.9.0 (D) ; Step: 20; Type: SQL.  Application failed. 
org.postgresql.util.PSQLException: Unterminated dollar quote started at position 102 in SQL CREATE OR REPLACE FUNCTION linenetamtrealinvoiceline(p_c_invoiceline_id numeric)
  RETURNS numeric AS
$BODY$
DECLARE
          v_amt numeric. Expected terminating $$
