### ISSUE TITLE
Create method to get non business days

### ISSUE THREAD

**Issue by RJPC** [adempiere/adempiere#1546]
Currently, there is no method with which non-business days that exist in a date range can be obtained.

**Comment by adaxa-steven** [comment]
Hi RJPC,
we had to make changes in this area because we wanted to see the actual business days available when doing replenishment calculations. We just used sql to add every day for the next 10 years to the non-business days table and then set Saturday and Sunday as active and Monday to Friday as Not Active. The the user could just tick any non-business days that fell between Monday and Friday as Active.  I realise that it makes more sense if we tick the business days as Active but we were trying to change as little as possible. Having all the days shown let us easily count the business days in the replenishment date range we were interested in.
The Create New Client process could ask which days are 'weekend' days and then populate the table ... or it could be a separate process... and doing this did not break anything else.

**Comment by yamelsenih** [comment]
Hi Steven here exist a method for resolved non business days. https://github.com/adempiere/adempiere/blob/develop/base/src/org/compiere/model/MCalendar.java#L177

**Comment by yamelsenih** [comment]
Now you can use it for Non business days:
<pre>TimeUtil.getNonBusinessDaysBetween(t1, t2);</pre>
<pre>TimeUtil.getNonBusinessDaysBetween(t1, t2, Calendar.SATURDAY, Calendar.SUNDAY);</pre>
Or it for Business Days:
<pre>TimeUtil.getBusinessDaysBetween(t1, t2);</pre>
<pre>TimeUtil.getBusinessDaysBetween(t1, t2, Calendar.MONDAY, Calendar.TUESDAY, Calendar.WEDNESDAY, Calendar.THURSDAY, Calendar.FRIDAY);</pre>

**Comment by RJPC** [comment]
Hi @yamelsenih 

The methods getBusinessDaysBetween and getNonBusinessDaysBetween they worked right.

**Comment by yamelsenih** [comment]
Thanks
