### ISSUE TITLE
HRProcess: flag to post individually for every employee

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#1552]
As of now the payment amount of a payroll is accumulated in the accounting.

Sometimes it is required to post the payment amount per employee. This is the case when for example a company applies this posting rule as a politic.

This behaviour can be controlled by a flag in HR_Process.

**Comment by e-Evolution** [comment]
@SusanneCalderon 

Can please set am imagen about the new flag

Why not define this new flag into the document type ?

**Comment by SusanneCalderon** [comment]
@e-Evolution 
The position of the flag in HR_Process was chosen to give the user direct access to this behaviour. It is allways updatable, so you can repost, considering the value of the flag.

If you place it in the documenttype you maybe get undesired behaviour in other HR_Processes which use the same document type.

**Comment by e-Evolution** [comment]
@SusanneCalderon 

Using this flag in the process is not appropriate since it is not is good idea  for the operating user to establish a purely accounting behavior. 

This also ignores of Adempiere security standard for accounting that any configuration that affects the accounting behavior is established by permission of a show Accounting role. if any user can set this flag without have show Accounting role then your ignore the of Adempiere security standard 

So once you define an accounting behavior it is not changing every time since it goes against an accounting principle of consistency.

My proposal if you want to introduce this functionality is that it can be defined by payroll not by each accounting a process, because if the accountant defined that the account fact are generate by  employee, it is not useful that the user who makes the payroll need to remember every period that the flag should activate.

**Comment by yamelsenih** [comment]
Please continue discussion here: https://github.com/adempiere/adempiere/pull/1841
