### ISSUE TITLE
Posting of material receipts before cost transactions have been generated should cause warning

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#167]
Material receipts can be posted where there are no cost transactions resulting in no facts generated but the document is marked "posted".  The doc status should be invalid or posting error so that it can be reposted once the cost information is available.

To see the error, from a fresh data import and migration, log in as Garden Admin and run the client accounting processor, then check any material receipt - they will have zero facts.  Match invoices will show that material receipts have not been posted yet.

Generate the cost transactions.  Material receipt are not reposted and have to be reposted manually or the accounting reset - which is overkill.

If the MRs were left with an error, then the documents could be fixed with the Resubmit Posting process.

**Comment by e-Evolution** [comment]
Hi Mike

We need to think that want in this case , because sometime you need that a cost is registered as  zero cost , if  we force that a document have not to complete a document if not have cost or accounting facts , it can cause a business process stop and not is good idea , So to avoid that a cost is not register and somebody forget, I modified of resubmit posting process, this way we warranty that if any document without cost it is set to re posting.

**Comment by mckayERP** [comment]
The issue may be with the order in which transactions are looked at when the cost details are created.  The current approach uses the transactions in order by the transaction ID (M_Transaction_ID).  This is OK in an ideal world but it doesn't match the GardenWorld data where there are sales (negative inventory) before products are received.  This is entirely acceptable in processes where the data entry on receipts happens after the fact but sales are in real time.  

If we take the transactions at the end of the day (acct date) and do all the incoming ones first and then the outgoing, ignoring the Transaction ID, the GardenWorld data works.  

The query in GenerateCostDetail is:

        sql.append("SELECT M_Transaction_ID , M_Product_ID FROM RV_Transaction ")
                .append(whereClause)
                //.append(" ORDER BY M_Product_ID ,  TRUNC( DateAcct ) , M_Transaction_ID , SUBSTR(MovementType,2,1) ")
                .append(" ORDER BY M_Product_ID ,  TRUNC( DateAcct ) , reversalline_id , SUBSTR(MovementType,2,1) Desc ");

I added the reversalline_id to ensure that the primary document is treated before the reversal regardless of the incoming/outgoing nature of the movementType.  Using this query, in GardenWorld, all MRs have the correct costs posted after the Generate Cost Detail process is run.

WDYT?

M

**Comment by e-Evolution** [comment]
Hola Mike!
The idea is that transaction are generate when happen using the cronologia real, We need id transaction to warranty that any Costing Method based on layer cost always be calculated ok. the big issue start with the exceptions , reverse transaction and incorrect data entry , it can damage the layer cost , this reason that I try always have a conologia in the transactions.

If user is little ordered , then I regenerate all transactions before the close end period is very convenient , a way to change the order to apply cost layer always is possible change the accounting date.
on the other hand I change the functionality resubmit posting to validate that all document with empty account fact can be marked to repost again.

Do you test please if this not work can try other approach. 

About the your patch , is necessary an intensive test because I not am sure if are work in all complex case that was considered to generate the cost transaction.

**Comment by mckayERP** [comment]
Still not working in Garden World.  With fresh seed, log in as garden admin, generate cost details, run the client accounting process and then look at the cost details for the plum tree - material costs only.

The order of the cost detail shows the sales ahead of purchases.  For the average invoice, there are no costs associated with the sales registered before the material receipt/invoice.  Then, the average invoice cost is calculated as $200/7 rather than $200/10 and the COGS of the next sale is $28.57 instead of $20.  While this will use up the cost of the inventory when all 7 remaining trees are sold, and total COGS will equal $200, it makes the margin on the sale of the trees look bad in the mean time.  Also, after that next sale, the Income Statement total COGS for the plum tree would show $28.57 rather than $80.

Would it not be better to have the Matching Invoice post a correction to COGS once the costs are known?  Something like:

- Current inventory -3, current material cost $0.
- Received 10 items for $200. Cost per item $20
- Update inventory to qty 7, and add $140 to product inventory.
- Update costs:  add $20*3 to COGS to account for past inventory sold - (or repost the associated shipments with the correct cost data).
- Update the cost details or add an adjustment of $60 such that the accumulated amount in $140 with quantity 7.

With this, the next sale of Qty 1 Plum Tree would show a COGS of $20 as expected and the Income Statement would show a total COGS of $80.

**Comment by adaxa-steven** [comment]
Hi Mike
rather than clutter up this ticket I have sent you an email with a lot of screen shots of a possible solution
Ultimately it comes down to a ending up posting like the following
![image](https://user-images.githubusercontent.com/15791084/47276826-cbf7df00-d605-11e8-83c3-811ae3efefa2.png)
This is a posting of an oncost invoice where part of the received goods have already been sold so part of the cost has to go to COGS rather than inventory.

Is that what you are trying to achieve?

regards

**Comment by mckayERP** [comment]
Thanks Steve.  Yes, but to do it without much manual effort on the part of the AP person.
