### ISSUE TITLE
Repeated running of the Generate Cost Transactions causes corruption of data

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#169]
Generate the cost transactions and then view the product cost details for a particular product.  Note the amounts.  Re run the Generate cost transaction process.  Refresh the product cost details and they will have changed.

**Comment by e-Evolution** [comment]
The Generate cost transaction re build of cost transaction and values based on account date of M_Transaction , The accountant some time entry early transaction this transaction move of cost (Average PO or AP), so while of account period is open of generate cost transaction re build of transaction cost if the account period is close then cost engine generate an adjustment cost.

The main goal is that transaction have the must right history cost that some country is very important to calculate of tax payment.

**Comment by mckayERP** [comment]
I found the generate costing process does not delete all the cost records.  The lastCostDetail can include future costDetails.  This creates a loop of ever increasing accumulated quantities each time GenerateCostTransaction is run.  A fix has been posted to adempiere-costing/adempiere.  I hope to get a few others to test and check the work before making a pull request back to the main repo.

**Comment by e-Evolution** [comment]
Hi Mike exist 2 way to delete old records, if you use  generate cost transaction or if you have activate adjustment cost in on from accounting schema. in case of generate cost transaction use of date in process to determinate from that date starting with delete transaction, in two case the cost engine only remove cost detail where of period is not close

**Comment by mckayERP** [comment]
I understand what the GenerateCostTransaction is trying to do. The problem is in the logic.  The process identifies all the products & transactions that have costs and then runs through a loop of the all schema,  cost methods and cost elements.  The first pass, it sets the where clause for the delete and then deletes for that set of dimensions.  But it does this only once per product. That works only if you generate the costs for one element of one method in one schema.  If there are multiple dimensions, the next element, method and schema are not deleted and show up as the lastCostDetail when creating the new cost detail.  You can see this in GardenWorld in the costs for the Plum tree.

Here is the main code - I've removed some lines to focus on the logic.

    public void generateCostDetail() {
        KeyNamePair[] transactions = getTransactionIdsByDateAcct();
        boolean processNewProduct = true;
        Trx dbTransaction = null;
        try {
            //Process transaction
            for (KeyNamePair keyNamePair : transactions) {
                int transactionId = keyNamePair.getKey();
                int transactionProductId = new Integer(keyNamePair.getName());
                //Detected a new product
                if (productId != transactionProductId) {
                    //commit last transaction by product
                    productId = transactionProductId;
                    processNewProduct = true;
                }
                MTransaction transaction = new MTransaction(getCtx(), transactionId, dbTransaction.getTrxName());
                // for each Account Schema
                for (MAcctSchema accountSchema : acctSchemas) {
                    // for each Cost Type
                    for (MCostType costType : costTypes) {
                        // for each Cost Element
                        for (MCostElement costElement : costElements) {
                            if (processNewProduct) {
                                applyCriteria(accountSchema.getC_AcctSchema_ID(),
                                        costType.getM_CostType_ID(), costElement.getM_CostElement_ID(),
                                        productId, p_DateAcct, p_DateAcctTo);
                                deleteCostDetail(dbTransaction.getTrxName());
                                processNewProduct = false;
                            }
                            generateCostDetail(accountSchema, costType, costElement, transaction);
                        }
                    }
                }
            }

**Comment by e-Evolution** [comment]
Hi Mike , currently the new cost engine allow have costing multiple in parallel for each accounting schema, So we now can have costing in multiples method (Average PO & Invoice, Standard , pending implement (FIFO, LIFO , Last Cost)), it is very important to business so that a lot important decision are take with this information ie we can get inventory valuation in different cost type.

So the logic should consider the generation the cost detail for each accounting schema, cost type , cost element.

ADempiere now support Cost's Dimension that have of last calculated cost by cost type, accounting schema , organization (it depend of Cost Level) , on the other hand the cost detail is generated by each inventory transaction , cost type , cost element , also here are maintained the cost's layer.
The accounting engine generate the accounting facts based on the cost type and costing method defined  in each  accounting schema.

I have a costing management manual in draft status , I would publish in ADempiere Library as we made with forecast management , will be great if you can review and once more can be my editor :-), 
WDYT?

**Comment by mckayERP** [comment]
More than happy to help.

Thanks.

Mike
