### ISSUE TITLE
Add index in the user window

### ISSUE THREAD

**Issue by RJPC** [adempiere/adempiere#1808]
ADempiere currently allows duplication of users

I propose to add an index by client and value

**Comment by e-Evolution** [comment]
No is good to define  an unique index beacuse the AD_User is also contact table, so the same contact can exist for multiple business partner.

This happen when hace group company that share contacts

**Comment by adaxa-steven** [comment]
Hi, 
We agree with Victor. You may have the same user and email address in 2 ad_users.  Consider 2 Clients which are related companies and have the same accountant.
This causes problems if you use the adempiere webstore because the email address is used to identify the user.  We added an 'iswebstoreuser' to ad_user with a unique constraint and changed the wesbstore code to look at that value. That change may be useful to add.
![image](https://user-images.githubusercontent.com/15791084/42542750-adc54db2-84eb-11e8-9f50-2a673d54fcf5.png)

**Comment by e-Evolution** [comment]
Dear @adaxa-steven Steven , I checked and this field exits, so may be only is included your code

Can you share the code? 

I can add to Adempiere

kind regards 
Victor

**Comment by adaxa-steven** [comment]
happy to share it ...  will ask for information when people come back from their influenza :-(

**Comment by yamelsenih** [comment]
Hi everybody, the index is added for (AD_Client_ID + Value) the webstore sould be indexed by email instead a unique value, i think that the modern app already used email as unique value for user.

Best regard
