### ISSUE TITLE
ValidLookup in MColumn should check for changes to the element that may temporarily invalidate the data.

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#200]
ValidLookup in MColumn should check for changes to the element that may temporarily invalidate the data.  If the element is changed, the column name and reference may also change.  Do not test for valid lookups if the element is changing and allow the save of the new element.  Wait for the other relevant changes before testing the validity of the lookup.

**Comment by e-Evolution** [comment]
I think that his validation is not right 

 	public static void validLookup(String p_ColumnName, int p_AD_Reference_ID, int p_AD_Reference_Value_ID) {
 		// For backwards compatibility with older XML, skip the validation of the lookup 
 		// if a migration script is running
-		if (Env.getContext(Env.getCtx(), "MigrationStepApplyInProgress").equals("Y") )
-			return;
+		//if (Env.getContext(Env.getCtx(), "MigrationStepApplyInProgress").equals("Y") )
+		//	return;
 
Ad should be removed, the validation not is the issue , I reviewed the migration script from 370 to a 380 and I could saw that the column AD_Reference_Value_ID have not value it is not is right for an column defined as Table reference, so we should modify the script xml and set a valid  AD_Reference_Value_ID, it happen because now the system validate that this reference is rightly defined.

this behaving should be the also when a column not is found as table using of conversion Supervisor_ID we should have a table called Supervisor  if not then the  validLookup is invalid

kind regards

**Comment by mckayERP** [comment]
Agreed. I don't have a fix for the AD_Reference_Value_ID though.   I'll start to post the suggested fixes shortly for the other aspects.
