### ISSUE TITLE
Field LandedCostType in LandedCost

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#2031]
For documentation it is convenient to distinguish between different types of distributed costs.
According to the incoterms for any mode of transport we generated a referencelist _LandedCostType_
1. - EXW – Purchase Costs
2. - DIS - Discounts
3. - ECD - Export customs declaration
4. - CPE - Carriage to port of export
5. - UPE - Unloading port of export
6. - LPE -Loading on vessel/airplane in port of export 
7. - FRE - Freight costs
8. - INS -Insurance 
9. - UPI - Unloading in port of import 
10. - LPI - Loading in port of import 
11. - CPD - Carriage to place of destination 
13. - ICC - Import customs clearance
14. - IDT -  Import duties and taxes
15. OTH Others

Costs 1 to 6 include FOB, 1 to 8 CIF.
The table _C_LandedCost_  has a new field _LandedCostType_, mandatory, with a default value _Others_

**Comment by e-Evolution** [comment]
@SusanneCalderon What is the difference of using a cost element?

Does the classification have any practical application or is it only for grouping information?

**Comment by SusanneCalderon** [comment]
1. Example, costing method average invoice, 2 providers, first provider is foreign, second provider is local.
Using costelements for costing every costelement is calculated seperatly. So after the first purchase I have costs for import customs. When I purchase the next items from a local provider I have no additional costs for import customs, but in the calculation of the overall costs these costs are still considered and not updated, because I do not have any invoice for this cost element which could be distributed as landed costs.
To avoid these efffect I mix different cost types in 1 cost element, in this example material costs. 
But for reporting purpose I have to distinguish between the cost types.
2. This classification is serves just for reporting and grouping.

**Comment by e-Evolution** [comment]
@SusanneCalderon , I understand, so you need a Landed Cost Type to filter the products that are linked with this landed cost, so I think that the best solution is to create a new table for M_LandedCostType, so any company can adding the landed cost type that they need. set as now a static list can be that is not applied for all case in all company or simply want management other elements.  so not should use you a list table because if is a way to order and group by landed cost type, the customer should have the freedom to create you landed cost type list with name and search key as they need. as now work the business partner group, product category, product group, product class, etc.

The Table based on the list are using when to implement a business logic for each element of the list as Delivery Rule, Invoice Rule

On the other hand, adding a new table M_ProductLandedCostType and link the Landed Cost Type with the product this way can be included as a parameter in the smart browser to apply landed cost distribution based in that products have the Landed Cost Type.

**Comment by adaxa-steven** [comment]
Hi Susanne, Victor,
I guess everyone has dealt with this issue in their own preferred way.  We just use Charge with a Flag to say "IsLandedCost" and then select the cost distribution type that we wish to use if this Charge is selected. You could have one Charge per item in Susanne's list.   If the costing method requires the line value to be added to inventory value, the account code on the Charge is ignored.  We also allowed an MR to be selected at the Invoice Header then the only thing the user had to do was enter the invoice line and select the correct Charge and then all the on-cost addition happened automatically.  The changes also handled the issue of .. purchase invoice qty=10, sell 4, then the landed cost invoice arrives ... so 40% of the cost goes to COGS and the remainder to inventory. 
If the code is useful let us know and we will confirm it is in SF... but our costing code i think is quite different these days.

**Comment by SusanneCalderon** [comment]
Hi @e-Evolution 
I understand your point of using a table instead of a list. I will change that.
Hi @adaxa-steven 
Thanks for your comment, I would love to see the code. Actually we are handling the case of allready sold(used) products in Doc_Invoice  and AverageCostEngine. 
The assetcosts calculated in AverageCostEngine is the cost per item multiplied with the items already in stock. The quantity is calculated with the corresponding Attribute Set Instances of the corresponding purchase transaction.
In Doc_Invoice the difference between the line costs and the assetcosts are applied in the account ACCTTYPE_P_CostAdjustment.
