### ISSUE TITLE
Project Status not visible after setting the Project Type

### ISSUE THREAD

**Issue by marcalwestf** [adempiere/adempiere#2327]
In the _Project_ Window the possibility of defining the current status of a project exists.

Due to some changes in the _Project_ module, which included changing the _Project Type_ structure (now controlling the _Project Status_)  and _Project Category_ (formerly containing the _Project Status_, now not used for it), this doesn't work: the list of _Project Status_ for a given project is always empty.

The reason is the _Dynamic Validation_ defined for column _C_ProjectStatus_ID_ from table _C_Project_.
The Dynamic Validation "C_ProjectStatus of Project Type" has the following validation code:
```
EXISTS (SELECT * FROM C_ProjectType pt 
INNER JOIN C_ProjectStatusCategory psc ON (pt.C_ProjectStatusCategory_ID=psc.C_ProjectStatusCategory_ID)
WHERE pt.C_ProjectType_ID=@C_ProjectType_ID@)
```
The new Dynamiv Validation should consider the new structure.
Here an example (I am sure, not the only one) of how it could work:
```
C_ProjectStatus.C_ProjectStatus_ID IN (SELECT ps.C_ProjectStatus_ID
FROM C_ProjectStatus  ps
INNER JOIN C_ProjectStatusCategory psc ON (ps.C_ProjectStatusCategory_ID=psc.C_ProjectStatusCategory_ID)
INNER JOIN C_ProjectType pt ON (psc.C_ProjectStatusCategory_ID=pt.C_ProjectStatusCategory_ID)
INNER JOIN C_Project p ON (pt.C_ProjectType_ID=p.C_ProjectType_ID)
WHERE p.C_Project_ID=@C_Project_ID@)
```
This worked on a project which had set a _Project Type_ referencing a _Project Status Category_ with status defined.

**Comment by e-Evolution** [comment]
@marcalwestf Hello Mario. Please indicate the steps to replicate the error because in my test it is working without a problem.

Project status works once a project type is assigned to a project and the project type has a project status category defined.

The project status is used to define the status to a project, phase or task.

The operation is similar to the status of requests for the request management functionality.


![image](https://user-images.githubusercontent.com/786968/52510275-efe52d80-2bc0-11e9-8241-bc5d146c775a.png)

![image](https://user-images.githubusercontent.com/786968/52510301-0e4b2900-2bc1-11e9-9464-f295be8a0aea.png)

![image](https://user-images.githubusercontent.com/786968/52510328-228f2600-2bc1-11e9-911e-37f6bcf207fe.png)

![image](https://user-images.githubusercontent.com/786968/52510337-35a1f600-2bc1-11e9-8c06-625f81792f91.png)

![image](https://user-images.githubusercontent.com/786968/52510354-43f01200-2bc1-11e9-976f-f0c94ef8f719.png)

![image](https://user-images.githubusercontent.com/786968/52510369-5407f180-2bc1-11e9-80c5-78ae9569b7fb.png)

**Comment by marcalwestf** [comment]
I tested again against a new seed and I didn't reproduce the error.
