### ISSUE TITLE
MPPCostCollector Class does not contains void functionality

### ISSUE THREAD

**Issue by Mbilalilyas** [adempiere/adempiere#234]
Void / Reversal functionality not exist in Cost Collector Window

**Comment by e-Evolution** [comment]
Cost collector not implement reverse or void logic
so that is very complex revert all operation that have an interaction with Manufacturing Order so if some entry operation was entry wrong,  then this can be fix with negative transaction

if the user should issue product a 100 each and delivery 120
then is simple now return 20 using same window only the delivery to -20
or if a user should receipt a finish good 10 but receipt 15
then is simple now only need receipt -5 , this way the system know net are 10

kids regards
