### ISSUE TITLE
Calculate for Not Realized Gain / Loss for Account Element  Multi-Currency

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#2354]
This process takes the accounting records until a closing date for all multi-currency accounting accounts of the balance in the source currency of the transaction is converted to the currency of the accounting scheme at the exchange rate of the closing date, the difference with the current balance balance in currency records a journal for the difference as loss or gain in exchange

**Comment by adaxa-steven** [comment]
Hi Victor. 
Are you just adopting what Adaxa did?  It sounds the same from your description. It has been working well for a couple of years. We normally do manual journals because the auto-created journal just creates many lines that add no value. An improvement would be to allow control of a level of summarisation in the created journal lines.

**Comment by e-Evolution** [comment]
@adaxa-steven Hi Steven

The process is new, but it is based on the experience of Adaxa and the improvements of OpenUp, since some accountants want to have a report with integration the result of Not Realized Gain / Loss for Multi-Currency , on the other hand the approach that I am using is based on the accounting records more than in documents and is calculated by difference, so it may or may not revert the last diary registered in the last period, that is already the decision of the accountant.

we are using the T_InvoiceGL  temporal table for generating the integration report and using table id and the record id to be able to obtain the report and detailed information for each document.

reference #2300

**Comment by adaxa-steven** [comment]
Good luck with it .. Note that the adaxa approach also reconciles what is shown in the aging report as at a particular date with what is in the GL at that date and this is very useful if you have AR or AP items in multiple foreign currencies and particularly if you also have multiple AR or AP control accounts because there is no other way in adempiere to demonstrate that the document based reports reconcile with the GL reports ... and then you get the restatement calculation as extra information on a per GL account code basis.  I can not imagine how you can do the same if starting form the GL information.
regards
Steven

**Comment by e-Evolution** [comment]
@adaxa-steven Dear Steven.

If in fact, I am following the Adaxa approach, which was taken by OpenUp to add the support detail.

My job was to refactor the code to the best development practices of ADempiere that we apply today.

also I am adding and testing this functionality to support of multiples accounts schema with difference currency.

Account Schema for USD
Account Schema for Pesos Colombianos
Account Schema for EUR

On the other hand, in my business case, the client manages funds allocated in projects, these funds are on balance sheet account, the resources of each fund are kept in the currency of origin USD, EUR, so the calculation of the loss and gain unrealized,  is required for these accounts.

In another business case, I have a client that uses ADempiere with a multi-schema and requires re-evaluating other accounts besides AP, AR, Banks.

So the detail is based on the original amount of the accounting history and its currency, so there is a way to get information support for the report.

In the current focus of ADempiere, the "Foreign Currency Account" flag is only enabled for bank accounts when it should be free to configure any account element, example prepayment customer.

So I think it's fine if the flag does not depend on whether it's a bank account or not, it should be possible to define any account in the balance generated with another currency

What do you think?
