### ISSUE TITLE
Same Print format but distinct report view

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#237]
If a user want have a same print format but with two where clause, the System administrator must create two print format, then if exist a change in the first print format, the same change must be reply in the second print format.

Is better if in the report window you has a combo box with all report view related to current table.

**Comment by e-Evolution** [comment]
The report in adempiere are created based on process , report view and print format , the process allows to define the filter parameters the report, the print form allows define the specific "Where Clause" necessary for a report, on the other hand , also exist those reports auto generated on fly, based on a Window and Tab , for this not need a process or report view. and the filters parameters can be defined using search window.
will great  enable the feature to change the report view using the same print format  that have as base the same table but with different report view , this way is not necessary create other print format, so that +1 vote for this feature

**Comment by yamelsenih** [comment]
See the new changes: [Spin Contribution: FR: Same Print Format with Distinct Report View](http://wiki.adempiere.net/Spin_Contribution:_FR:_Same_Print_Format_with_Distinct_Report_View)
