### ISSUE TITLE
ERROR: function uuid_generate_v1() does not exist

### ISSUE THREAD

**Issue by younex1** [adempiere/adempiere#2439]
This error occurs when try to establish webui-connection:
ERROR: function uuid_generate_v1() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Where: PL/pgSQL function getuuid() line 27 at RETURN; State=42883; ErrorCode=0

This function won´t be created in postgres-dump shipped with latest adempiere.

This SQL will fix the issue:

CREATE OR REPLACE FUNCTION uuid_generate_v1()
RETURNS uuid
AS '$libdir/uuid-ossp', 'uuid_generate_v1'
VOLATILE STRICT LANGUAGE C;

**Comment by PraponAon** [comment]
Hi @younex1 
If you use Linux. Try to install the Extensions and Additions first.
For example, my system is CentOS 6.10 & Postgresql 9.6
   yum update
   yum install postgresql96-server    postgresql96-contrib

**Comment by yamelsenih** [comment]
Hi @younex1 maybe you can see it issue: #2247 also it: #1836 
The problem is that your DB don't have support for extension of UUID, you can resolve it wit:

<pre>
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
</pre>

https://github.com/adempiere/adempiere/pull/2012/files#diff-a588f226cb3008631808e03c533955ccR1
