### ISSUE TITLE
Smart Browse does not get the hidden fields in Selection Browse

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#257]
When a field is mark like **Identifier** and it is not displayed, in T_Selection_Browse it is not inserted

**Comment by e-Evolution** [comment]
Hi Yamel!

This change no is right .

1.- a Smart browser not can get the grid field based on column name because a column name can be duplicate in any column in SB, this reason because I use 

GridField gridField = (GridField) browserRows.getValue(row, col);

It warranty that always get the right value based on in row and column 

Use this logic is complete error , first because the column can have same name , second because a calculate column have not AD_Column_ID so that is optional because is the idea that you can add any column as need.

GridField gridField = (GridField) browserRows.getValueOfColumn(row, field.getAD_View_Column().getAD_Column().getColumnName());

**Comment by e-Evolution** [comment]
this changes introducing  a bug #/308
