### ISSUE TITLE
[Bug Report] Rounded Price and Quantity for Order / Invoice

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#2975]
#### Previous data
Product information required:
- Product: 
  - Code: TP-001
  - Name Toilet Paper 9"
  - Product UOM: Each
  - Conversion: 1 Pack (4 Units) = 4 units

#### Steps to reproduce
1. Create a Order
2. Add new line
3. Quantity Entered (Unit of purchase): **5 Packs**
4. Quantity Ordered (Uom of Product): **20 Each**
5. Price Entered (Price on Pack): **$ 182,193.74**
6. Price Actual (Price on Each): **$ 45,548.435**

#### Expected behavior
- Total Line: **$ 910,968.70**
- Form used: Total Line = **Price Entered (Price on Pack)** * **Quantity Entered (Unit of purchase)** ~ **$ 182,193.74** * **5** = **$ 910,968.70**

#### Current bad result:

- Total Line: **$ 182,193.80**
- **Price Entered (Price on Pack)** / **Quantity Ordered (UOM of Product)**: **$ 9,109.687**
- **Rounded Unit price (ADempiere Internal calc)**: **$ 45,548.435** ~ **$ 45,548.44**
- **Form used**: **Total Line** = (Price Entered (**182,193.74**)  / Conversion Rate (**4**)) * Quantity Ordered (**20**) ~ **182,193.74** / **4** ~ [**45,548.435** ~ rounded is **45,548.44**] * **20** = **$ 182,193.80**

#### Other relevant information
- Your OS: Debian
- Java version: 1.8
- ADempiere version: 3.9.3
- Browser [e.g. chrome, safari]: Chrome
- Browser Version [e.g. 22]
- DB Provider: PostgreSQL
- DB version: 10x

**Comment by marcalwestf** [comment]
hi @yamelsenih  I cannot reproduce the error.
I took Adempiere without your changes first.

Here what I did:
1.- Create product _TP-001_ with UOM _Each_ and add a conversion rule:
![Selection_335](https://user-images.githubusercontent.com/1789408/75103111-d3dddf80-55bb-11ea-92da-1727a1f15c6b.png)

2- Add the product to the Purchase price list:
![Selection_336](https://user-images.githubusercontent.com/1789408/75103122-fcfe7000-55bb-11ea-8bf2-5564af1c86cc.png)

3.- I created a purchase order for a vendor with a purchase price list:
![Selection_337](https://user-images.githubusercontent.com/1789408/75103167-d0972380-55bc-11ea-8856-5f97fdc48358.png)

4.- Then added a line as you describe:
![Selection_338](https://user-images.githubusercontent.com/1789408/75103187-06d4a300-55bd-11ea-8ce6-6f3fa42f6ee9.png)

5. In the end. I added a line with the UOM _4Pack_:
![Selection_339](https://user-images.githubusercontent.com/1789408/75103223-6632b300-55bd-11ea-92ca-d7c8f9e56b1c.png)

In my opinion, the calculation is correct: in either case the _Line Net Amount_ = 182,193.74; this is what I would expect. In the second step, the price 36,438.748 has been accommodated to the new UOM.
I do not understand how you should come to 910,968.70

Perhaps I'm missing one step? Thanks!

Funny enough, with your changes I get exactly the same results!!!

**Comment by yamelsenih** [comment]
Hi Mario you can test with price on 0?

Best Regards

**Comment by marcalwestf** [comment]
Sure @yamelsenih 

1.- Set the prices in the Purchase Price List to 0:
![Selection_340](https://user-images.githubusercontent.com/1789408/75114844-49c76280-561f-11ea-8a56-cd4d1dd8db59.png)

2.- Created a new Order with same header (no image required).

3.- Created an Order line with UOM=_Each_, but due to the fact that price in price list was==0, I had to put the price:
![Selection_341](https://user-images.githubusercontent.com/1789408/75114876-9612a280-561f-11ea-94c2-6a9e9737d331.png)

4.- Created another order line, only this time the UOM=_4Pack_ and entered the price accordingly to the conversion:
![Selection_342](https://user-images.githubusercontent.com/1789408/75114930-df62f200-561f-11ea-992c-17883ab873fa.png)

The result is the same as if there is a price in the price list.
So it seems to me that the behavior is the same with this pull request and without.

Otherwise, looking at the code, there is a distinction and it seems to me more formal, and thus desirable, but I cannot get the situation to test....

**Comment by yamelsenih** [comment]
![Screenshot_20200223-124717](https://user-images.githubusercontent.com/2333092/75116080-fa8f2b00-563a-11ea-8fcf-0825e81f0086.png)

Hi Mario, just see the calculator, a simple product of quantity (4Pack) 4Pack * Price (4Pack) 

The expected result is 182.193.7 instead

**Comment by marcalwestf** [comment]
hi @yamelsenih now that you changed in the description the unit price to
Price Actual (Price on Each): **$ 45,548.435**

I will test again and report my findings.

**Comment by marcalwestf** [comment]
Additionally, the UOM of the 4 Pack must be = 2 (I had 4!!) . This can be found doing single-step on CalloutOrder.amt().
If you have the precision set to 4, then the error cannot be reproduced.
![Selection_344](https://user-images.githubusercontent.com/1789408/75166467-865f9080-56e9-11ea-9c77-ca39d0bd7a30.png)

Actually this PR takes you the need of adding precision just because of the UOM.
