### ISSUE TITLE
Issue when the costing level is defined as Warehouse

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#320]
The issue is caused by  that not was mark of parent link for warehouse in cost dimension

**Comment by yamelsenih** [comment]
Hi @e-Evolution i have a problem with it change, when a material receipt is create and completed, it return a error DB, the following error is:
<pre>
===========> DB.executeUpdate: INSERT INTO M_Cost (AD_Client_ID,AD_Org_ID,C_AcctSchema_ID,Created,CreatedBy,CumulatedAmt,CumulatedQty,CurrentCostPrice,CurrentQty,FutureCostPrice,IsActive,IsCostFrozen,M_AttributeSetInstance_ID,M_CostElement_ID,M_CostType_ID,M_Product_ID,Updated,UpdatedBy) VALUES (1000000,0,1000000,TO_TIMESTAMP('2016-04-21 19:49:05','YYYY-MM-DD HH24:MI:SS'),100,0,0,0,0,0,'Y','N',0,1000000,1000000,1000046,TO_TIMESTAMP('2016-04-21 19:49:05','YYYY-MM-DD HH24:MI:SS'),100) [WFP_cf3f79c8-c8c5-47ae-a258-4a9d56db26e4] [193]
org.postgresql.util.PSQLException: ERROR: null value in column "m_warehouse_id" violates not-null constraint
  Detail: Failing row contains (1000000, 0, 1000046, 1000000, 1000000, 1000000, 0, Y, 2016-04-21 19:49:05, 100, 2016-04-21 19:49:05, 100, 0, 0, 0, 0, 0, null, 0, 0, null, N, null, null).; 
</pre>
![image](https://cloud.githubusercontent.com/assets/2333092/14727925/cdf76a1e-07f9-11e6-846d-5aff68c4844c.png)

I think that the warehouse in the cost should be mandatory just the level cost is warehouse.

Best Regards

**Comment by yamelsenih** [comment]
When you want rollback the XML it lauch the following error:
<pre>
Rollback failed.  org.postgresql.util.PSQLException: ERROR: argument of WHERE must be type boolean, not type numeric   Position: 32
</pre>
It is caused by the where clause in following statement
<pre>
ALTER TABLE M_COST ADD CONSTRAINT M_COST_PKEY PRIMARY KEY(AD_CLIENT_ID, AD_ORG_ID, M_PRODUCT_ID, M_COSTTYPE_ID, C_ACCTSCHEMA_ID, M_COSTELEMENT_ID, M_ATTRIBUTESETINSTANCE_ID);
DELETE FROM M_WAREHOUSE WHERE **M_WAREHOUSE_ID**
</pre>

Always is nice test the rollback in the custom statement.
