### ISSUE TITLE
[Bug Report] Move the Quote to Invoice menu order

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#3332]
## Bug report
- Some new functionality may be the create production order or shipment move the original menu

![image](https://user-images.githubusercontent.com/786968/105614033-2e635b00-5d8c-11eb-8789-26587498d57e.png)

#### Steps to reproduce
1.- Create a install based on 3.9.3
2.- Apply all XML Migration Script 
3.- Review the main menu , this was change incorrectly. 

#### Other relevant information
- Your OS: MacOS
- Java version: JDK 8
- ADempiere version: 3.9.4
- Browser  safari
- DB Provider: PG
- DB version: 12.5

**Comment by marcalwestf** [comment]
hi @e-Evolution  Victor, I did as you required.
I confirm that after applying the XMLs up to commit 3295f72cfe311c471c98ac0b2a903f3be222bd37 there is a difference to Adempiere 393.

The difference is -as you put it- that after applying the XMLs, the _Shipments_ folder comes before the _Sales Orders_ folder, whereas, in Adempiere 393, the _Sales Orders_ folder comes before the _Shipments_ folder.

I suppose that in order to get it done, either the XML that moved the folder has to be corrected or another XML correcting this has to be written. Preferrable is the former option.
