### ISSUE TITLE
DocumentNo Always Updatable in C_Order

### ISSUE THREAD

**Issue by niclopup** [adempiere/adempiere#3733]
## Bug report

The DocumentNo in the Sales Order is defined as Always Updatable. 

The change was made the 25/01/2022

#### Screenshot or Gif
![DocNo in C_Order](https://user-images.githubusercontent.com/31936815/153476915-b32c9bb8-da53-46bf-b2f2-9c77eebfc7db.png)

https://user-images.githubusercontent.com/31936815/153476927-b5ec11ee-d379-4882-a4a2-09c015859f5e.mp4

The test was made in 

https://adqa.prolinux.cl/webui/

Data Base: adempiere

**Comment by marcalwestf** [comment]
@niclopup  I think I am the culprit.
Due to a test reason, I did change the column but didn't correct it.
I left it in the original cofiguration.

The correct configuration is in the official seed:
![imagen](https://user-images.githubusercontent.com/1789408/153494731-a577eb49-d773-44c5-ae20-399a840cac69.png)

Closing this issue.
