### ISSUE TITLE
Organization Tax Exempt

### ISSUE THREAD

**Issue by niclopup** [adempiere/adempiere#3894]
## Organization Tax Exempt

Some organizations has dont accept the recongnition of any tax, either for sales or for purchase, so the hole import is fot sales or for costs (Tax Expempt).

I understand that this funcionality could be managed with the checks of "SO Tax Expempt" and "PO Tax Exempt" but there is some cases that in one company there could be differents organizations that one has the normal definitions of Taxes while other organization has no taxes.

The problem exist when they share the same Business Partner so one options could be duplicate the Business Partner, one exempt in the organization exempt and an other Business partner in the other organization without the check. This i think isn´t ok so i propose the follow enhancement

![Screenshot_2022-05-26_09-37-32](https://user-images.githubusercontent.com/31936815/170557434-25a27063-4d3c-45be-a8e6-04154ee44b9b.png)

#### Describe the solution you'd like

Create the checks of "SO Tax Expempt" and "PO Tax Exempt" in the Organization so it could be managed not only by the business partner but also by organization.

![Screenshot_2022-05-26_09-37-32](https://user-images.githubusercontent.com/31936815/170557434-25a27063-4d3c-45be-a8e6-04154ee44b9b.png)

**Comment by e-Evolution** [comment]
I checked the current model for those two fields within the whole system and I did not find any use of any of the fields within the system, so I can understand that these two fields are more of reference information since there is no behavior of the functionality of taxes.

Now I think that your business case can be solved by creating a business partner for each organization and then linking the organization with the business partner and to each business partner putting what information you require.

**Comment by niclopup** [comment]
Hi Victor @e-Evolution , thank you for your answer.

We based our suggestion in the "Tax" class in adbase/develop. 

I think that those checks are they used in this Class to set the tax

Here i show:

![Tax java 1](https://user-images.githubusercontent.com/31936815/171252508-e716f551-7c24-4a9e-9a53-4be97d4d775f.png)
![Tax java 2](https://user-images.githubusercontent.com/31936815/171252514-d1df7dd0-db44-4d3d-a302-09ed031c5498.png)

I wait for you comments.

thanks

**Comment by nsarlabos** [comment]
Finally, the implemented solution has been the following.

A business partner linked to the organization is defined, and the sales-exempt and purchase-exempt checks are marked as appropriate.

With the modifications made in the "Tax.java" class, if the business partner of the document to be created (invoice, order, etc.) does not have the exempt check marked (sale or purchase depending on the document in question), then the exempt check will go to look for the business partner linked to the organization of the document.

**Comment by e-Evolution** [comment]
@nsarlabos Hi here my change request.

Currently this functionality should be explicitly defined with a parameter, something like VALIDATE_EXEMPT_TAXES_BASED_ON_ORGANIZATION : Validate exempt taxes based on organization into of Sys Config

The important reason for this is because Adempiere's tax engine is based on document addresses, this is because it supports coniguration of taxes by territory, that's why knowing the country, region, state, county are crucial. for countries that define if a tax is exempt or not by the address.

Since this new setting when a tax is saved, it overrides the standard functionality when a business partner is attached to an organization and the tax expeption flag overrides a saved rate.

While this functionality is valuable, it should be enabled by a system configuration flag explicitly, the implementer being aware that he wishes to ignore the standard ADempiere tax engine functionality.

Otherwise you can cause a serious problem considering this as an automatic configuration.
