### ISSUE TITLE
[Bug Report] The RUN_DBRestore.sh not work for linux 

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#4050]
## Bug report
[Bug Report] The RUN_DBRestore.sh not work for linux 

#### Steps to reproduce
1.- When try execute the RUN_DBRestore.sh this restore Adempiere_pg.dmp vs ExpDat.dmp 
2.- The big problem is that the database never is restart with last RUN_DBExport.sh

#### Link to minimal reproduction
The bug is now in last 3.9.4 nightly build 

#### Expected behavior
The backup should be restore in database

#### Other relevant information
- Your OS: macOS
- Java version: 17
- ADempiere version: 3.9.4 nightly build 
- DB Provider: PG
- DB version: 15.1

#### Additional context
Bug introducing by @yamelsenih  in this #1858

**Comment by marcalwestf** [comment]
@e-Evolution  Victor, the changes of the commit https://github.com/adempiere/adempiere/commit/04eb5297bc206d937d3a16344b99247162e5cd52 in this issue are backward-compatible with earlier versions: restoring _$ADEMPIERE_HOME/utils/RUN_DBRestore.sh_ and _$ADEMPIERE_HOME/utils/PostgreSQL/DBRestore.sh_ enables users to run a backup as it was always possible. 

Unluckily, the implementation of _Github CI/CD actions_ changed both  _$ADEMPIERE_HOME/utils/RUN_DBRestore.sh_ and _$ADEMPIERE_HOME/utils/PostgreSQL/DBRestore.sh_ and made restore not possible from _Expdat.dmp_, but from _Adempiere_pg.dmp_.
So this commit is OK.

**But** it disrupts the **Github CI/CD actions** aimed to start from seed and migrate all XMLs and so make sure every XML file change leaves the seed always "clean".
I believe you agree that implementing the **Github CI/CD actions** is important to the project.

In order to keep the best of both worlds (keep restore backward compatible and also maintain the Github CI/CD actions of testing seed and all migration XMLs), I suggest not only restoring _$ADEMPIERE_HOME/utils/RUN_DBRestore.sh_ and _$ADEMPIERE_HOME/utils/PostgreSQL/DBRestore.sh_ (your commit), but also **change the files involved in Github CI/CD** so that we get both functionalities.

I imagine creating an additional script e.g. _RUN_DBRestoreSeed.sh_, which would restore from seed and it would be used in the Github CI/CD actions. Or adding a parameter to _RUN_DBRestore.sh_, with default ("restore from _ExpDat.dmp_") and called from Github CI/CD actions with the parameter changed to restore from _Adempiere_pg.dmp_.

This should be done in one single Pull Request. Concretely this would mean that you should add to this commit the necessary changes to get Github CI/CD done.

**Comment by marcalwestf** [comment]
after a private chat with @e-Evolution , we agreed that it is much easier than I stated: in order to implement the build from seed, it is enough to use **RUN_ImportAdempiere.sh** instead of **RUN_DBRestore.sh**, as **RUN_ImportAdempiere.sh** already  uses **Adempiere_pg.dmp**.

This means, that additionally to this commit, only the action where **RUN_DBRestore.sh** is used should be changed to **RUN_ImportAdempiere.sh**.
