### ISSUE TITLE
Replication add support for organization and role

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#450]

**Comment by marcalwestf** [comment]
I think the definition of AD_PInstance_Log_ID is missing, because the commit c242510d1b9c67c943166cf851d018b912dbde7c references to AD_PInstance_Log_ID, but this column is not defined neither in the database nor in the Application Dictionary.
In order for this commit to be complete the XML and Application Dictionary entries for  AD_PInstance_Log_ID must be defined.

**Comment by marcalwestf** [comment]
Correction: the XML scripts 0142_390_Add_IsIgnoreMigration_Attribute_to_Table.xml and 0173_445_SolveWrongDefinitionsOnAD.xml from commit c41a71c7f11c0fecd7da39c1025a5ad4b7f19153 must be applied. These commits includes the definition of AD_PInstance_Log_ID.

**Comment by e-Evolution** [comment]
1.- Add support to role security to execute a replication strategy
2.- The approach change from old replication version , now the replication strategy not is defined in client or organization , to define that replication strategy need apply can define by role and organization , if want apply to all organization can use *
