### ISSUE TITLE
Add connection support to MariaDB

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#464]
Currently the MariaDB connection in ADempiere is unsupported, jus exists a DB connection with MySQL.

**Comment by yamelsenih** [comment]
The current support is for mariadb-java-client-1.4.6.jar

**Comment by yamelsenih** [comment]
Is nice to have a DBEngine_MariaDB for migration tools

**Comment by gvilauy** [comment]
Yamel, the jdbc driver for mariadb is missing on the hotFix 2 branch.
This causes errors when you sincronize the project.
Can you Fix it ?

**Comment by yamelsenih** [comment]
Hi @gvilauy what is your IDE? i am using Eclipse and the build.xml for build the project is change for add support to MariaDB, also i write a change in the classpath.

Tell me if you need other.

Thank you.

**Comment by gvilauy** [comment]
I use IntelliJ

**Comment by e-Evolution** [comment]
@yamelsenih  Yamel you re factor can cause problem with before installation 

The class ConfigurationData.java before use the database in lowercase , now was change to upper case, this cause problem with before installation , when execute a RUN_silentsetup.sh , the reason is that the AdempiereEnvTemplete.properties had the database with lowercase name

Do you check all consequences that can cause the change of lowercase and upper case database name ?

Please if mariaDB not is stable still, then use a branch or pull request.

**Comment by yamelsenih** [comment]
Hi @e-Evolution do you have tha bad chage?

**Comment by e-Evolution** [comment]
Hi @yamelsenih you can see here the database name are in lowercase [AdempiereEnvTemplate.properties](https://github.com/adempiere/adempiere/blob/hotfix/3.8.0%23002/install/Adempiere/AdempiereEnvTemplate.properties#L16)
