### ISSUE TITLE
M_Product_ID is Mandatory (Production)

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#491]
Product_ID field missing (mandatory) in the window production does not allow save.

**Comment by yamelsenih** [comment]
Hi @wdtz thank you for report it, i will look the bug.

**Comment by yamelsenih** [comment]
The bug is because the M_Product_ID column of M_Production table is mandatory, also the M_Locator_ID is mandatory like is showed in the next image:
![issue2004](https://cloud.githubusercontent.com/assets/2333092/17707052/947445b4-63ac-11e6-914a-c13988555b71.png)

<pre>
DB.saveError: DBExecuteError - ERROR: null value in column "m_locator_id" violates not-null constraint
  Detail: Failing row contains (1000001, 11, 50001, Y, 2016-08-16 12:27:06, 100, 2016-08-16 12:27:06, 100, AA, null, 2016-08-16 00:00:00, N, N, N, N, null, null, null, null, null, null, null, 1000000, null, null, 0, null, null, null, N)
</pre>

**Comment by yamelsenih** [comment]
Also is fixed a problem with bad distribution of field in the window, see the image:
![issue2005](https://cloud.githubusercontent.com/assets/2333092/17775437/3c3928a8-6526-11e6-922d-8a2092f625eb.png)

**Comment by wdtz** [comment]
I do not understand is why there must be the field M_Product_ID in  M_Production (Headline), usually I can do  multiple production plans (Products to Produce) do not understand why there obligatoriness, normally is required the product in the plan.
