### ISSUE TITLE
Parameter Panel & SmartBrowser criteria do not set gridField value

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#495]
From comments in #462:

Search criteria don't seem to be applied and the values aren't remembered.  

Tested on Payment Selection, Business Partner or Doc Type do not affect the search.

I think this has to do with the handling of the vetoable change events in the criteria fields. This is a bit of a messy design in adempiere as there is the field (display), field editor, and gridField which all have to share the same value. If the user changes the field editor, it fires a vetoable change event but does not set its own value. The vetoable change listeners can veto the change but mostly sync the girdField with the new value (See the GridController). The vetoable change in the GridController also handles multiple selection. The gridField value change triggers a property change which the field listens to and uses to set its value and to set the display of the new value.

In the VBrowserSearch, the vetoable change listener does not sync the gridField so the model does not get the new value. This means that the criteria is not applied to the search and the value is not set in the field when the criteria are expanded again.

I made a change to add a property change listener function in the VBrowserSearch class and moved the current veto code there and then copied some of the GridController vetoable change code into the vetoable change listener in VBroswerSearch. This last sets the value in the gridField which was the missing piece. The search criteria now affect the search and the criteria field remember their values.

**Comment by yamelsenih** [comment]
Hi @mckayERP i test it and find a bug with parameters, example:
A SB have two parameters
- **Param1**.
- **Param2**.

The **Param2** have a default value like **@SQL=SELECT t.Value FROM Test t WHERE t.Test_ID = @Param1@**, when the default value in the **Param2** is getting, it throw a warning because the **@Param1@** was not found in the context.

After load all parameter, i find the context and i look the **@Param1@**. It is loaded in the context after load all parameters.

Best Regards.

**Comment by e-Evolution** [comment]
Related https://github.com/adempiere/adempiere/pull/462

**Comment by yamelsenih** [comment]
It is worked
