### ISSUE TITLE
Box opening (opening balance)

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#528]
POS starts with a cash balance of payments for changes, this still is not allowed in the POS?

**Comment by e-Evolution** [comment]
Hi @wdtz the cash balance is management using a dummy bank account for each POS , so you can transfer money should and other account bank using the standard functionality bank transfer

**Comment by yamelsenih** [comment]
Hi i think that it should be embedded into POS like is the payment inside POS

**Comment by wdtz** [comment]
I understand, it's just that at this point do not see as balancing a box with an opening balance additionally with your answer another question arises.

as will be the relation in Terminal and CashBook,It is now mandatory?

**Comment by e-Evolution** [comment]
Mi recomendación is no use cash book ,  we have best management using bank statement functionality.

No is good practice show of balance from POS system , because this information only the be know by supervisor , the POS operator not should know the cash balance because need delivery the total register in POS.

this way the POS operator not have way to adjustment the payment to match with cash balance.

**Comment by wdtz** [comment]
I understand, however if opening of my POS begins with a cash balance(Money Change), to balance the balance the supervisor have to know:

The opening balance
The total Sales
Cash expenditures (These cases can also happen where there is a cash outflow of money)

all this I generate my final balance that is my closed box or delivery accounts:

Total Sales.
Remaining money.
Missing money

**Comment by e-Evolution** [comment]
Then is simple you can use Bank Statement Close in POS process action


![captura de pantalla 2016-08-18 a las 2 52 59 p m](https://cloud.githubusercontent.com/assets/786968/17788534/b4726488-6553-11e6-8820-e4d22130377b.png)

In bottom can see the total sales , open balance and payment amount for each POS Terminal , this action only are enable for supervisor using pin 

![captura de pantalla 2016-08-18 a las 2 52 59 p m](https://cloud.githubusercontent.com/assets/786968/17788497/9a5e5ec6-6553-11e6-980c-28fcab14c385.png)

**Comment by wdtz** [comment]
I try, and generates the following error.
![image](https://cloud.githubusercontent.com/assets/9578152/17788932/e597177a-655d-11e6-9bff-406baee27b18.png)

**Comment by e-Evolution** [comment]
You have a POS obsolete binary , the method or WBrowser change in core.

**Comment by yamelsenih** [comment]
Hi it is changed? I think that should have back support compatibility

**Comment by e-Evolution** [comment]
the field IsSOTrx was added as  parameter of constructor , this is important to management some functionality using  context variable based on sales transaction or not , when a smart browser is call from a window.

**Comment by e-Evolution** [comment]
On the other hand all code was re factory , my suggestion is should testing from adempiere project 
POS is now integrate

**Comment by yamelsenih** [comment]
Victor if the constructor is changed then is better make overcharge the current constructor instead modify, if you not passed like parameter the issotrx then just set to false and work

**Comment by yamelsenih** [comment]
Is better add support to current constructor instead modify

**Comment by e-Evolution** [comment]
Yamel yes , but this can be incorrect because this parameter is mandatory , and is based in of  called from menu , then can not a default value , the same Smart browser can have a different behavior if is transaction sales or not

You can see new Browser Sales Order and Browser Purchase Order , the smart browser is one but have a different menu , so when the menu call, it  send of sales transaction to class's contructor

the original constructor not should exist , because can cause a inconsistent behavior.

On the other hand the POS is new for ADempiere core , no exist back compatibility if yet not is released

**Comment by yamelsenih** [comment]
OK just for a future is better make a overcharge instead modify.
Best regards

**Comment by yamelsenih** [comment]
This is resolved
