### ISSUE TITLE
NPE caused in InfoBPartner when the Name column is sorted

### ISSUE THREAD

**Issue by mckayERP** [adempiere/adempiere#545]
Open the Info BPartner window, click on the name column header to resort the column.  The first row will be the summary row.  A NPE occurs at line 441 when calling getSelectedRowKey();

**Comment by dixon22ma** [comment]
Hi @mckayERP this issue is under review.

**Comment by marcalwestf** [comment]
The compiler throws an exception when the variable _m_C_BPartner_ID_ (which is defined as an int) gets **null** when calling _getSelectedRowKey()_.

Suggestion:
In class _InfoBPartner_, method _recordSelected(int key)_, instead of 
_m_C_BPartner_ID = getSelectedRowKey();_

replace it with the following code:
		_Integer tmpRowKey = getSelectedRowKey();
		m_C_BPartner_ID = (tmpRowKey==null?0:tmpRowKey);_

In other classes like _InfoProduct_, the ID is set to 0 when the _getSelectedRowKey()_ returns a null.

As this is a core function, I'd like to know your opinion before committing.
I tested this change and works well.

**Comment by marcalwestf** [comment]
With commit abc8131c7af2614fd36692182abb6ce1a355d92c this bug does disappear: now it is possible to sort any  column of the InfoBPartner form.
In my opinion, this issue can be closed.

**Comment by yamelsenih** [comment]
Hi @All it is solved, i test it and is worked
![arbol_68](https://user-images.githubusercontent.com/2333092/26998217-309d294c-4d4f-11e7-9d74-29ee261dd693.png)
