### ISSUE TITLE
Validate Balance (Immediate Transfer)

### ISSUE THREAD

**Issue by wdtz** [adempiere/adempiere#563]
The immediate transfer should validate the bank balance, should not allow transfer  more than what you have in account.

![image](https://cloud.githubusercontent.com/assets/9578152/17948995/64cef626-6a21-11e6-948c-ed7945a15f28.png)

![image](https://cloud.githubusercontent.com/assets/9578152/17949003/711fcae0-6a21-11e6-8078-90a80b0afc30.png)

**Comment by armenrz** [comment]
The validation you ask will be hard to implement because it relies on how up-to-date your user to complete the Bank Statement. Because the current balance is only updated at that point. And also I have bad experience for Bank Current Balance. If user does not enter Bank Statement chronologically in exact order of actual date, you will end up with wrong current balance.

**Comment by yamelsenih** [comment]
This is unnecessary because the bank statement update bank balance, all movement only have a transit movement
