### ISSUE TITLE
Process parameter don't have a parameter like only information

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#566]
The process parameter don't have a attribute for create a field like only reference for view, example:

I want show a field (**Only information**) with the bank account balance, but it field is only for view information in the process parameter panel instead filter the query report or send to process class.

It is like the chage done in #556

**Comment by marcalwestf** [comment]
Hi Yamel, 
I don't understand the usage of this parameter. I read also the issue  #556 and didn't get it also.
Does this field exist? If you want to show it, this could be programmed int the code. If you do not filter, the content would be anything.. Perhaps I am lloking at the wrong side.
Thanks
Mario

**Comment by yamelsenih** [comment]
Hi @marcalwestf it is util for make parameters that you not need, example: you can have a parameter for a report and it is not used for filter the report.

**Comment by marcalwestf** [comment]
since this commit it is not possible to see contents of parameters which are defined as lists like for example the System Element _DocStatus_.
![20160831_parameter](https://cloud.githubusercontent.com/assets/1789408/18135801/5ae73472-6f60-11e6-9523-7a7ce016cb61.png)

When the process is clicked and the parameter list pops up I notice in Eclipse the following issue:

_===========> MLookup.run: AD_Ref_List.Value, 3000322 : Loader - SELECT NULL, AD_Ref_List.Value,trl.Name, AD_Ref_List.IsActive FROM AD_Ref_List INNER JOIN AD_Ref_List_Trl trl  ON (AD_Ref_List.AD_Ref_List_ID=trl.AD_Ref_List_ID AND trl.AD_Language='es_SV') WHERE AD_Ref_List.AD_Reference_ID=135 AND C_BPartner.IsSummary='N'  AND EXISTS (SELECT * FROM C_Order o INNER JOIN C_OrderLine l ON (o.C_Order_ID=l.C_Order_ID)
WHERE C_BPartner.C_BPartner_ID=o.C_BPartner_ID AND o.DocStatus NOT IN ('DR','IP') AND l.QtyOrdered <> l.QtyInvoiced AND o.IsSOTrx='Y')
 ORDER BY 3 [37]
org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "c_bpartner"
  Position: 232; State=42P01; ErrorCode=0
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)_

When I do a git checkout and st the working directory to the commit 54409ea7831473fe2632864e61a10ad5392b086f , which is the one **before** this one, then the behavior I describe disappears.

This happens to all parameters which are defined as lists. Parameters defined as table, table direct etc. are not affected.
This behavior is funny because studying the changes of this commit I cannot see anything that would cause what I described.

**Comment by Raul-mz** [comment]
Hi @marcalwestf the error was resolved, you can test.

**Comment by marcalwestf** [comment]
Just tested change. Now it works.
