### ISSUE TITLE
When try change of Tab in Migration window get this error

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#640]
![captura de pantalla 2016-10-25 a la s 11 01 45](https://cloud.githubusercontent.com/assets/786968/19693799/7842ee68-9aa2-11e6-8d66-98c788c407a8.png)

**Comment by taherelhossin** [comment]
This error because "**NewValue**" column in migration data tab is marked as **AutoComplete - true** and this is not supported in ZK yet .. if you un-check this flag in application dictionary it will work well.

Note: this is the only column in all adempiere which has **Reference type** = **string** and auto complete marked **true**

**Comment by Raul-mz** [comment]
Hi @e-Evolution you can test this.?

**Comment by yamelsenih** [comment]
I test it and worked.
