### ISSUE TITLE
SmartBrowser To Process Orders in Batch

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#758]

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon, can you change the XML number?

The current number is **01680_757_Constraint_failed_Insurance_Detail.xml** is nice if your XML will be **01690_758<Your XML Name>.xml**

Best Regard.

**Comment by e-Evolution** [comment]
Hi @SusanneCalderon 

I detected duplicate functionality in this class

https://github.com/adempiere/adempiere/blob/hotfix/3.8.0%23002/base/src/org/compiere/process/OrderBatchProcess.java

We should use same code logic to process when is execute from a Smart Browser or directly from a menu option.

The other hand the news process that are added need be implement the new API Abstract Process

kind regards

**Comment by yamelsenih** [comment]
Hi @SusanneCalderon @e-Evolution both class are the same functionality, the problem is when you try generate abstract process class, it is because the Smart Browse for process order have differents parameters.

I think that the new functionality can replace the old process, then the definitive process for batch order should be the Smart browse instead menu process.

The SB for process batch order can use de old menu process referenced on **org.compiere.process.OrderBatchProcess** and just is need make some changes over it.

Is my suggestion, if you agree whit me then i can change it.

Best regard
