### ISSUE TITLE
method don't search completed process

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#771]
The method getConcept (String conceptValue, String payrollValue,Timestamp from,Timestamp to) just search concept values without discrimination by document status, if you have a payroll on **Draft** status is probable that it can be add to sum of query

<pre>
 AND EXISTS (SELECT 1 FROM HR_Process p  
			INNER JOIN HR_Period pr ON (pr.HR_Period_id=p.HR_Period_ID)
			WHERE HR_Movement.HR_Process_ID = p.HR_Process_ID
			AND p.HR_Payroll_ID=?)
</pre>

It can be changed by:

<pre>
 AND EXISTS (SELECT 1 FROM HR_Process p  
			INNER JOIN HR_Period pr ON (pr.HR_Period_id=p.HR_Period_ID)
			WHERE HR_Movement.HR_Process_ID = p.HR_Process_ID
			AND p.DocStatus IN('CO', 'CL')
			AND p.HR_Payroll_ID=?)
</pre>

**Comment by e-Evolution** [comment]
Hi,  @yamelsenih good catch!

I agree, then we can create a new method to called only processed movements getConcept (String value, Boolean processed) and overload for MHRProcess.

On the other hand, What happen with some concept that need be getting and that are a manual entry, this case the payroll process is in the process, so in this case the second query not return some result and this not is right because as the payroll process the status document is inprocess.

**Comment by yamelsenih** [comment]
@e-Evolution when you want get a concept like manual can use the **getConcept(String)** instead **getConcept (String, String,Timestamp,Timestamp)**

**Comment by e-Evolution** [comment]
but then change to get movement based on doc status is only for when is for the range.

I remember to added new method helper in MHRMovement , will be good only have here to get any history.
