### ISSUE TITLE
System Config reversal invoice DocNo

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#887]
Can you please elaborate ?

**Comment by adaxa-steven** [comment]
sorry - no idea

**Comment by e-Evolution** [comment]
Hi Steven , the information that I have is  #951(Adaxa) but not have more description in script  148_AD_SYSCONFIG-reversal_invoice_DocNo.xml

**Comment by adaxa-steven** [comment]
https://idempiere.atlassian.net/browse/IDEMPIERE-148
Allow reversal invoice to use DocNo^ instead of consuming an invoice #
"when you reverse an invoice iDempiere is consuming an invoice number - this is not good in some countries/implementations.
So, the proposal here is to allow a mechanism (SysConfig) configurable per client to use DocNo^ as the reversal DocNo instead of consuming a new #
Proposed Sysconfig key: Invoice_ReverseUseNewNumber (defaulting to Y for backward compatibility)
Regards,
Carlos Ruiz"

**Comment by yamelsenih** [comment]
Hi @All what is the source code change for it? I have a implemented where the flag is in Document Type table instead of System Configurator, it allow define the behavior for each documents, example:

- You can have a document type named Delivery that the reversal is created with ^.
- Also you can have a document type named Delivery New that the reversal is created with new document no.

**Comment by e-Evolution** [comment]
@yamelsenih  may be @marcalwestf know the specific change because it was based in the xml script but the source code should are included in code 

@marcalwestf do you know what the source code?

**Comment by yamelsenih** [comment]
I has been added to:
- Shipment/Receipt
- Inventory Movement
- Production
- Journal
- Journal Batch
- Invoice
- Payment
