### ISSUE TITLE
Payment Allocation must be done in pairs

### ISSUE THREAD

**Issue by yamelsenih** [adempiere/adempiere#89]
I open Payment Allocation Form and read the status bar "Prefer selecting a matching invoice and payment pair and process each at time", i think that the model class must ensure that all payment allocations are process like pair
![issue8](https://cloud.githubusercontent.com/assets/2333092/11112232/2d2dbf6a-88e3-11e5-8fa6-59e4709aa6a5.png)

**Comment by yamelsenih** [comment]
Is very cleaning and more easy for development and functional user when the allocation are pair

**Comment by e-Evolution** [comment]
HI Yamel, I think that you need multiple selection, the reason is that you can have a big payment that can be assign a multiples invoice or vs.

The good practice is first select of payment and next of invoice until difference is zero.

If we only allow in pairs , I can not imagine choose a payment and 50 invoice each time , the prices would be very long.

kind regards

**Comment by yamelsenih** [comment]
Hi @e-Evolution yes, i said that in GUI must be the same but when the allocations is processed, its must be inside model class like pair.

**Comment by yamelsenih** [comment]
Nothing for it
