### ISSUE TITLE
Add Relative Period To Column In Performance Report Column

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempiere#894]
Can you please elaborate #3050(Adaxa)?

**Comment by adaxa-steven** [comment]
see document attached to 899.
... allows a single column to add the values from (say) period -4 to period -1  and get the figures for the 3 month period before the current period ... note that if not used the 'to period' must be NULL  ... this should have been fixed by a migration script and probably was.

**Comment by e-Evolution** [comment]
[Adaxa Reporting Changes 2016-09.pdf](https://github.com/adempiere/adempiere/files/880905/Adaxa.Reporting.Changes.2016-09.pdf)

**Comment by e-Evolution** [comment]
this new column is working , is very important define the period relative to in 0 or null because the result can be different , to back compatibility you can define the period relative to as null and this will working as before
