### ISSUE TITLE
WTrialBalance: ValidationCode for field accountFrom and accountTo are ambigious when system language is different from base language

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere#979]
Class WTrialBalance
Line 257

 ```
MLookup lookupUser1 = MLookupFactory.get(Env.getCtx(),
						form.getWindowNo(),
						col_User1_ID,
						DisplayType.Table,
						Env.getLanguage(Env.getCtx()),
						"User1_ID",
						ReferenceID_of_User1_ID,
						false,
						"IsActive='Y' AND AD_Client_ID="+m_AD_Client_ID );
```
Should be ""C_ElementValue.IsActive='Y' AND C_ElementValue.AD_Client_ID="+m_AD_Client_ID );"

**Comment by e-Evolution** [comment]
Hi Susanne @SusanneCalderon 
The trial balance report should allow any dimension no only user1
![trialbalancedrillablereport](https://cloud.githubusercontent.com/assets/786968/25054000/6277e548-2120-11e7-8f1c-7a4fd51cc27e.png)

**Comment by adaxa-steven** [comment]
Victor, It could allow for more dimensions however we do not propose to change it as it meets our needs now. As mentioned elsewhere we use UserList1 as Cost Centre so this report is designed to give info on org+cost centre+account code and nothing else.

If you want you want to extend I would do it this way.  Add a flag on Cube for "this cube is used for the drillable trial balance".  The drillable trial balance can then easily give a warning if no Cube exists or  flagged. Make the flag unique .. ie only one cube can be "Y".  Allow a particular number of dimensions to be displayed in the "drillable trial balance" ... lets assume six available fields.   Populate the filter fields that are displayed in the header with the dimensions that are ticked as Y in the Cube ticked as the one to be used in the drillable trial balance. If more than 6 are ticked then display the first six based on sequence number in the window.

Note that this was intended to be a very fast report.  It is fast because the number of rows in the cube of org+cost centre+account (+month) is usually quite small.  If you start adding extra dimensions then the number of rows will go up very quickly and the speed is likely to go down very quickly!  I have not checked if there are indexes on the Cube data ... probably should be.
regards..

**Comment by e-Evolution** [comment]
Hi Steven!

Why not add the Cube as parameter this way the user can select under your requirements.

My intension was ask about the an implementation  more general , because other companies can be more import the activity dimension , project , or campaigning .

About the fact acct I think that now Portgresql and Oracle support materialized view , so we would migrate the current views to materialized view and solve the proforma issue.

kind regards

**Comment by SusanneCalderon** [comment]
I already comitted the additional field cube, Victor.
