### ISSUE TITLE
en setup.bat escogiendo la base de datos oracleXE existen los siguientes errores:

### ISSUE THREAD

**Issue by lbetanzo** [adempiere/adempiere#985]
en setup.bat escogiendo la base de datos oracleXE existen los siguientes errores:
en Adempiere.properties en la tile 28 no aparece el type que debe ser Oracle 
Connection=xyzCConnection[name\=SERX32WIN10PRO{localhost-xe-adempiere},AppsHost\=SERX32WIN10PRO,AppsPort\=1099,type\=,DBhost\=localhost,DBport\=1521,DBname\=xe,BQ\=false,FW\=false,FWhost\=,FWport\=0,UID\=adempiere,PWD\=adempiere]
Connection=xyzCConnection[name\=SERX32WIN10PRO{localhost-xe-adempiere},AppsHost\=SERX32WIN10PRO,AppsPort\=1099,type\=Oracle,DBhost\=localhost,DBport\=1521,DBname\=xe,BQ\=false,FW\=false,FWhost\=,FWport\=0,UID\=adempiere,PWD\=adempiere]
                                                                                                                     xxxxxxx
en AdempiereEnv.Properties tambien esta mal en oracleXE                                                                                                                     
la linea 29 esta ADEMPIERE_DB_PATH=OracleXE
y deve ser ADEMPIERE_DB_PATH=oracleXE
la linea 41 es ADEMPIERE_DB_TYPE=OracleXE
y debe ser ADEMPIERE_DB_TYPE=oracleXE

en el archivo MyEnviroment.bat en la linea 27 esta @SET ADEMPIERE_DB_PATH=OracleXE
y debe estar @SET ADEMPIERE_DB_PATH=oracleXE

en la line 32 esta @SET ADEMPIERE_DB_HOME=C:\Users\admin\Documentos\Adempiere\utils\OracleXE
y debe esta @SET ADEMPIERE_DB_HOME=C:\Users\admin\Documentos\Adempiere\utils\oracleXE

**Comment by testiranje1234** [comment]
try with change localhost to ip address (localhost->192.168.xxx.xxx)

2017-04-15 19:03 GMT+02:00 lbetanzo <notifications@github.com>:

**Comment by yamelsenih** [comment]
Hi @lbetanzo i write a change for it, please test it and send us your results

**Comment by yamelsenih** [comment]
Please test it and tell us if exists a error

**Comment by e-Evolution** [comment]
Hi Yamel , this change cause a lot the problem for deployment of ADempiere using Oracle.

The reason is that the bash script i.e.  RUN_ImportAdempiere try search the path for OracleXE but the current directory are as oracleXE and the script is sensible upper case.

The solution is revert this list of commits or modify the structure directory.

I know that window not is sensible to upper case but in unix environment 	elif [ "$dbVendor" == "OracleXE" ] not work with oracleXE that is current name for oracle script directory.

Current error

root@bda691693788:/u01/app/Adempiere/utils# ./RUN_ImportAdempiere.sh 

Import ADempiere Seed Database

The database vendor oracleXE is not supported.
The seed file (undefined) could not be loaded.
Please make sure it exists and you have read permissions.

**Comment by e-Evolution** [comment]
To fix I manually to changed the $ADEMPIERE_DB_PATH=OracleXE and move from oracleXE directory to OracleXE

**Comment by yamelsenih** [comment]
Hi I make very hard work for use OracleXE instead oracleXE. Just is need change the RUN_ImportAdempiere.sh

**Comment by e-Evolution** [comment]
I found the problem some reason the git not detect the change the upper case directory when the commit was made the merge.

To solve this problem I made:

Remove the current directory from source code
`rm -rf ./utils `

And update the repository code using :

`git checkout release/3.9.0 -f`

kind regards
Victor

**Comment by testiranje1234** [comment]
Oracle make path structure for oracle XE 10 g o xe n /usr/lib/oracle/xe /    ..app/oracle/product/10.2.0/server/bin/imp oracle 11g xe have different path /u01/app/oracle/product/11.2.0/xe/
I m very happy when will it came oracle 12 express trying to found new path of installation :-1:
